module Ionicons = {
  [@bs.module "@expo/vector-icons"]
  external js : ReasonReact.reactClass = "Ionicons";

  [@bs.deriving jsConverter]
  type name = [
    | [@bs.as "ios-add"] `undefined
    | [@bs.as "ios-add-circle"] `undefined
    | [@bs.as "ios-add-circle-outline"] `undefined
    | [@bs.as "ios-airplane"] `undefined
    | [@bs.as "ios-alarm"] `undefined
    | [@bs.as "ios-albums"] `undefined
    | [@bs.as "ios-alert"] `undefined
    | [@bs.as "ios-american-football"] `undefined
    | [@bs.as "ios-analytics"] `undefined
    | [@bs.as "ios-aperture"] `undefined
    | [@bs.as "ios-apps"] `undefined
    | [@bs.as "ios-appstore"] `undefined
    | [@bs.as "ios-archive"] `undefined
    | [@bs.as "ios-arrow-back"] `undefined
    | [@bs.as "ios-arrow-down"] `undefined
    | [@bs.as "ios-arrow-dropdown"] `undefined
    | [@bs.as "ios-arrow-dropdown-circle"] `undefined
    | [@bs.as "ios-arrow-dropleft"] `undefined
    | [@bs.as "ios-arrow-dropleft-circle"] `undefined
    | [@bs.as "ios-arrow-dropright"] `undefined
    | [@bs.as "ios-arrow-dropright-circle"] `undefined
    | [@bs.as "ios-arrow-dropup"] `undefined
    | [@bs.as "ios-arrow-dropup-circle"] `undefined
    | [@bs.as "ios-arrow-forward"] `undefined
    | [@bs.as "ios-arrow-round-back"] `undefined
    | [@bs.as "ios-arrow-round-down"] `undefined
    | [@bs.as "ios-arrow-round-forward"] `undefined
    | [@bs.as "ios-arrow-round-up"] `undefined
    | [@bs.as "ios-arrow-up"] `undefined
    | [@bs.as "ios-at"] `undefined
    | [@bs.as "ios-attach"] `undefined
    | [@bs.as "ios-backspace"] `undefined
    | [@bs.as "ios-barcode"] `undefined
    | [@bs.as "ios-baseball"] `undefined
    | [@bs.as "ios-basket"] `undefined
    | [@bs.as "ios-basketball"] `undefined
    | [@bs.as "ios-battery-charging"] `undefined
    | [@bs.as "ios-battery-dead"] `undefined
    | [@bs.as "ios-battery-full"] `undefined
    | [@bs.as "ios-beaker"] `undefined
    | [@bs.as "ios-bed"] `undefined
    | [@bs.as "ios-beer"] `undefined
    | [@bs.as "ios-bicycle"] `undefined
    | [@bs.as "ios-bluetooth"] `undefined
    | [@bs.as "ios-boat"] `undefined
    | [@bs.as "ios-body"] `undefined
    | [@bs.as "ios-bonfire"] `undefined
    | [@bs.as "ios-book"] `undefined
    | [@bs.as "ios-bookmark"] `undefined
    | [@bs.as "ios-bookmarks"] `undefined
    | [@bs.as "ios-bowtie"] `undefined
    | [@bs.as "ios-briefcase"] `undefined
    | [@bs.as "ios-browsers"] `undefined
    | [@bs.as "ios-brush"] `undefined
    | [@bs.as "ios-bug"] `undefined
    | [@bs.as "ios-build"] `undefined
    | [@bs.as "ios-bulb"] `undefined
    | [@bs.as "ios-bus"] `undefined
    | [@bs.as "ios-business"] `undefined
    | [@bs.as "ios-cafe"] `undefined
    | [@bs.as "ios-calculator"] `undefined
    | [@bs.as "ios-calendar"] `undefined
    | [@bs.as "ios-call"] `undefined
    | [@bs.as "ios-camera"] `undefined
    | [@bs.as "ios-car"] `undefined
    | [@bs.as "ios-card"] `undefined
    | [@bs.as "ios-cart"] `undefined
    | [@bs.as "ios-cash"] `undefined
    | [@bs.as "ios-cellular"] `undefined
    | [@bs.as "ios-chatboxes"] `undefined
    | [@bs.as "ios-chatbubbles"] `undefined
    | [@bs.as "ios-checkbox"] `undefined
    | [@bs.as "ios-checkbox-outline"] `undefined
    | [@bs.as "ios-checkmark"] `undefined
    | [@bs.as "ios-checkmark-circle"] `undefined
    | [@bs.as "ios-checkmark-circle-outline"] `undefined
    | [@bs.as "ios-clipboard"] `undefined
    | [@bs.as "ios-clock"] `undefined
    | [@bs.as "ios-close"] `undefined
    | [@bs.as "ios-close-circle"] `undefined
    | [@bs.as "ios-close-circle-outline"] `undefined
    | [@bs.as "ios-cloud"] `undefined
    | [@bs.as "ios-cloud-circle"] `undefined
    | [@bs.as "ios-cloud-done"] `undefined
    | [@bs.as "ios-cloud-download"] `undefined
    | [@bs.as "ios-cloud-outline"] `undefined
    | [@bs.as "ios-cloud-upload"] `undefined
    | [@bs.as "ios-cloudy"] `undefined
    | [@bs.as "ios-cloudy-night"] `undefined
    | [@bs.as "ios-code"] `undefined
    | [@bs.as "ios-code-download"] `undefined
    | [@bs.as "ios-code-working"] `undefined
    | [@bs.as "ios-cog"] `undefined
    | [@bs.as "ios-color-fill"] `undefined
    | [@bs.as "ios-color-filter"] `undefined
    | [@bs.as "ios-color-palette"] `undefined
    | [@bs.as "ios-color-wand"] `undefined
    | [@bs.as "ios-compass"] `undefined
    | [@bs.as "ios-construct"] `undefined
    | [@bs.as "ios-contact"] `undefined
    | [@bs.as "ios-contacts"] `undefined
    | [@bs.as "ios-contract"] `undefined
    | [@bs.as "ios-contrast"] `undefined
    | [@bs.as "ios-copy"] `undefined
    | [@bs.as "ios-create"] `undefined
    | [@bs.as "ios-crop"] `undefined
    | [@bs.as "ios-cube"] `undefined
    | [@bs.as "ios-cut"] `undefined
    | [@bs.as "ios-desktop"] `undefined
    | [@bs.as "ios-disc"] `undefined
    | [@bs.as "ios-document"] `undefined
    | [@bs.as "ios-done-all"] `undefined
    | [@bs.as "ios-download"] `undefined
    | [@bs.as "ios-easel"] `undefined
    | [@bs.as "ios-egg"] `undefined
    | [@bs.as "ios-exit"] `undefined
    | [@bs.as "ios-expand"] `undefined
    | [@bs.as "ios-eye"] `undefined
    | [@bs.as "ios-eye-off"] `undefined
    | [@bs.as "ios-fastforward"] `undefined
    | [@bs.as "ios-female"] `undefined
    | [@bs.as "ios-filing"] `undefined
    | [@bs.as "ios-film"] `undefined
    | [@bs.as "ios-finger-print"] `undefined
    | [@bs.as "ios-fitness"] `undefined
    | [@bs.as "ios-flag"] `undefined
    | [@bs.as "ios-flame"] `undefined
    | [@bs.as "ios-flash"] `undefined
    | [@bs.as "ios-flash-off"] `undefined
    | [@bs.as "ios-flashlight"] `undefined
    | [@bs.as "ios-flask"] `undefined
    | [@bs.as "ios-flower"] `undefined
    | [@bs.as "ios-folder"] `undefined
    | [@bs.as "ios-folder-open"] `undefined
    | [@bs.as "ios-football"] `undefined
    | [@bs.as "ios-funnel"] `undefined
    | [@bs.as "ios-gift"] `undefined
    | [@bs.as "ios-git-branch"] `undefined
    | [@bs.as "ios-git-commit"] `undefined
    | [@bs.as "ios-git-compare"] `undefined
    | [@bs.as "ios-git-merge"] `undefined
    | [@bs.as "ios-git-network"] `undefined
    | [@bs.as "ios-git-pull-request"] `undefined
    | [@bs.as "ios-glasses"] `undefined
    | [@bs.as "ios-globe"] `undefined
    | [@bs.as "ios-grid"] `undefined
    | [@bs.as "ios-hammer"] `undefined
    | [@bs.as "ios-hand"] `undefined
    | [@bs.as "ios-happy"] `undefined
    | [@bs.as "ios-headset"] `undefined
    | [@bs.as "ios-heart"] `undefined
    | [@bs.as "ios-heart-dislike"] `undefined
    | [@bs.as "ios-heart-empty"] `undefined
    | [@bs.as "ios-heart-half"] `undefined
    | [@bs.as "ios-help"] `undefined
    | [@bs.as "ios-help-buoy"] `undefined
    | [@bs.as "ios-help-circle"] `undefined
    | [@bs.as "ios-help-circle-outline"] `undefined
    | [@bs.as "ios-home"] `undefined
    | [@bs.as "ios-hourglass"] `undefined
    | [@bs.as "ios-ice-cream"] `undefined
    | [@bs.as "ios-image"] `undefined
    | [@bs.as "ios-images"] `undefined
    | [@bs.as "ios-infinite"] `undefined
    | [@bs.as "ios-information"] `undefined
    | [@bs.as "ios-information-circle"] `undefined
    | [@bs.as "ios-information-circle-outline"] `undefined
    | [@bs.as "ios-jet"] `undefined
    | [@bs.as "ios-journal"] `undefined
    | [@bs.as "ios-key"] `undefined
    | [@bs.as "ios-keypad"] `undefined
    | [@bs.as "ios-laptop"] `undefined
    | [@bs.as "ios-leaf"] `undefined
    | [@bs.as "ios-link"] `undefined
    | [@bs.as "ios-list"] `undefined
    | [@bs.as "ios-list-box"] `undefined
    | [@bs.as "ios-locate"] `undefined
    | [@bs.as "ios-lock"] `undefined
    | [@bs.as "ios-log-in"] `undefined
    | [@bs.as "ios-log-out"] `undefined
    | [@bs.as "ios-magnet"] `undefined
    | [@bs.as "ios-mail"] `undefined
    | [@bs.as "ios-mail-open"] `undefined
    | [@bs.as "ios-mail-unread"] `undefined
    | [@bs.as "ios-male"] `undefined
    | [@bs.as "ios-man"] `undefined
    | [@bs.as "ios-map"] `undefined
    | [@bs.as "ios-medal"] `undefined
    | [@bs.as "ios-medical"] `undefined
    | [@bs.as "ios-medkit"] `undefined
    | [@bs.as "ios-megaphone"] `undefined
    | [@bs.as "ios-menu"] `undefined
    | [@bs.as "ios-mic"] `undefined
    | [@bs.as "ios-mic-off"] `undefined
    | [@bs.as "ios-microphone"] `undefined
    | [@bs.as "ios-moon"] `undefined
    | [@bs.as "ios-more"] `undefined
    | [@bs.as "ios-move"] `undefined
    | [@bs.as "ios-musical-note"] `undefined
    | [@bs.as "ios-musical-notes"] `undefined
    | [@bs.as "ios-navigate"] `undefined
    | [@bs.as "ios-notifications"] `undefined
    | [@bs.as "ios-notifications-off"] `undefined
    | [@bs.as "ios-notifications-outline"] `undefined
    | [@bs.as "ios-nuclear"] `undefined
    | [@bs.as "ios-nutrition"] `undefined
    | [@bs.as "ios-open"] `undefined
    | [@bs.as "ios-options"] `undefined
    | [@bs.as "ios-outlet"] `undefined
    | [@bs.as "ios-paper"] `undefined
    | [@bs.as "ios-paper-plane"] `undefined
    | [@bs.as "ios-partly-sunny"] `undefined
    | [@bs.as "ios-pause"] `undefined
    | [@bs.as "ios-paw"] `undefined
    | [@bs.as "ios-people"] `undefined
    | [@bs.as "ios-person"] `undefined
    | [@bs.as "ios-person-add"] `undefined
    | [@bs.as "ios-phone-landscape"] `undefined
    | [@bs.as "ios-phone-portrait"] `undefined
    | [@bs.as "ios-photos"] `undefined
    | [@bs.as "ios-pie"] `undefined
    | [@bs.as "ios-pin"] `undefined
    | [@bs.as "ios-pint"] `undefined
    | [@bs.as "ios-pizza"] `undefined
    | [@bs.as "ios-planet"] `undefined
    | [@bs.as "ios-play"] `undefined
    | [@bs.as "ios-play-circle"] `undefined
    | [@bs.as "ios-podium"] `undefined
    | [@bs.as "ios-power"] `undefined
    | [@bs.as "ios-pricetag"] `undefined
    | [@bs.as "ios-pricetags"] `undefined
    | [@bs.as "ios-print"] `undefined
    | [@bs.as "ios-pulse"] `undefined
    | [@bs.as "ios-qr-scanner"] `undefined
    | [@bs.as "ios-quote"] `undefined
    | [@bs.as "ios-radio"] `undefined
    | [@bs.as "ios-radio-button-off"] `undefined
    | [@bs.as "ios-radio-button-on"] `undefined
    | [@bs.as "ios-rainy"] `undefined
    | [@bs.as "ios-recording"] `undefined
    | [@bs.as "ios-redo"] `undefined
    | [@bs.as "ios-refresh"] `undefined
    | [@bs.as "ios-refresh-circle"] `undefined
    | [@bs.as "ios-remove"] `undefined
    | [@bs.as "ios-remove-circle"] `undefined
    | [@bs.as "ios-remove-circle-outline"] `undefined
    | [@bs.as "ios-reorder"] `undefined
    | [@bs.as "ios-repeat"] `undefined
    | [@bs.as "ios-resize"] `undefined
    | [@bs.as "ios-restaurant"] `undefined
    | [@bs.as "ios-return-left"] `undefined
    | [@bs.as "ios-return-right"] `undefined
    | [@bs.as "ios-reverse-camera"] `undefined
    | [@bs.as "ios-rewind"] `undefined
    | [@bs.as "ios-ribbon"] `undefined
    | [@bs.as "ios-rocket"] `undefined
    | [@bs.as "ios-rose"] `undefined
    | [@bs.as "ios-sad"] `undefined
    | [@bs.as "ios-save"] `undefined
    | [@bs.as "ios-school"] `undefined
    | [@bs.as "ios-search"] `undefined
    | [@bs.as "ios-send"] `undefined
    | [@bs.as "ios-settings"] `undefined
    | [@bs.as "ios-share"] `undefined
    | [@bs.as "ios-share-alt"] `undefined
    | [@bs.as "ios-shirt"] `undefined
    | [@bs.as "ios-shuffle"] `undefined
    | [@bs.as "ios-skip-backward"] `undefined
    | [@bs.as "ios-skip-forward"] `undefined
    | [@bs.as "ios-snow"] `undefined
    | [@bs.as "ios-speedometer"] `undefined
    | [@bs.as "ios-square"] `undefined
    | [@bs.as "ios-square-outline"] `undefined
    | [@bs.as "ios-star"] `undefined
    | [@bs.as "ios-star-half"] `undefined
    | [@bs.as "ios-star-outline"] `undefined
    | [@bs.as "ios-stats"] `undefined
    | [@bs.as "ios-stopwatch"] `undefined
    | [@bs.as "ios-subway"] `undefined
    | [@bs.as "ios-sunny"] `undefined
    | [@bs.as "ios-swap"] `undefined
    | [@bs.as "ios-switch"] `undefined
    | [@bs.as "ios-sync"] `undefined
    | [@bs.as "ios-tablet-landscape"] `undefined
    | [@bs.as "ios-tablet-portrait"] `undefined
    | [@bs.as "ios-tennisball"] `undefined
    | [@bs.as "ios-text"] `undefined
    | [@bs.as "ios-thermometer"] `undefined
    | [@bs.as "ios-thumbs-down"] `undefined
    | [@bs.as "ios-thumbs-up"] `undefined
    | [@bs.as "ios-thunderstorm"] `undefined
    | [@bs.as "ios-time"] `undefined
    | [@bs.as "ios-timer"] `undefined
    | [@bs.as "ios-today"] `undefined
    | [@bs.as "ios-train"] `undefined
    | [@bs.as "ios-transgender"] `undefined
    | [@bs.as "ios-trash"] `undefined
    | [@bs.as "ios-trending-down"] `undefined
    | [@bs.as "ios-trending-up"] `undefined
    | [@bs.as "ios-trophy"] `undefined
    | [@bs.as "ios-tv"] `undefined
    | [@bs.as "ios-umbrella"] `undefined
    | [@bs.as "ios-undo"] `undefined
    | [@bs.as "ios-unlock"] `undefined
    | [@bs.as "ios-videocam"] `undefined
    | [@bs.as "ios-volume-high"] `undefined
    | [@bs.as "ios-volume-low"] `undefined
    | [@bs.as "ios-volume-mute"] `undefined
    | [@bs.as "ios-volume-off"] `undefined
    | [@bs.as "ios-walk"] `undefined
    | [@bs.as "ios-wallet"] `undefined
    | [@bs.as "ios-warning"] `undefined
    | [@bs.as "ios-watch"] `undefined
    | [@bs.as "ios-water"] `undefined
    | [@bs.as "ios-wifi"] `undefined
    | [@bs.as "ios-wine"] `undefined
    | [@bs.as "ios-woman"] `undefined
    | [@bs.as "logo-android"] `undefined
    | [@bs.as "logo-angular"] `undefined
    | [@bs.as "logo-apple"] `undefined
    | [@bs.as "logo-bitbucket"] `undefined
    | [@bs.as "logo-bitcoin"] `undefined
    | [@bs.as "logo-buffer"] `undefined
    | [@bs.as "logo-chrome"] `undefined
    | [@bs.as "logo-closed-captioning"] `undefined
    | [@bs.as "logo-codepen"] `undefined
    | [@bs.as "logo-css3"] `undefined
    | [@bs.as "logo-designernews"] `undefined
    | [@bs.as "logo-dribbble"] `undefined
    | [@bs.as "logo-dropbox"] `undefined
    | [@bs.as "logo-euro"] `undefined
    | [@bs.as "logo-facebook"] `undefined
    | [@bs.as "logo-flickr"] `undefined
    | [@bs.as "logo-foursquare"] `undefined
    | [@bs.as "logo-freebsd-devil"] `undefined
    | [@bs.as "logo-game-controller-a"] `undefined
    | [@bs.as "logo-game-controller-b"] `undefined
    | [@bs.as "logo-github"] `undefined
    | [@bs.as "logo-google"] `undefined
    | [@bs.as "logo-googleplus"] `undefined
    | [@bs.as "logo-hackernews"] `undefined
    | [@bs.as "logo-html5"] `undefined
    | [@bs.as "logo-instagram"] `undefined
    | [@bs.as "logo-ionic"] `undefined
    | [@bs.as "logo-ionitron"] `undefined
    | [@bs.as "logo-javascript"] `undefined
    | [@bs.as "logo-linkedin"] `undefined
    | [@bs.as "logo-markdown"] `undefined
    | [@bs.as "logo-model-s"] `undefined
    | [@bs.as "logo-no-smoking"] `undefined
    | [@bs.as "logo-nodejs"] `undefined
    | [@bs.as "logo-npm"] `undefined
    | [@bs.as "logo-octocat"] `undefined
    | [@bs.as "logo-pinterest"] `undefined
    | [@bs.as "logo-playstation"] `undefined
    | [@bs.as "logo-polymer"] `undefined
    | [@bs.as "logo-python"] `undefined
    | [@bs.as "logo-reddit"] `undefined
    | [@bs.as "logo-rss"] `undefined
    | [@bs.as "logo-sass"] `undefined
    | [@bs.as "logo-skype"] `undefined
    | [@bs.as "logo-slack"] `undefined
    | [@bs.as "logo-snapchat"] `undefined
    | [@bs.as "logo-steam"] `undefined
    | [@bs.as "logo-tumblr"] `undefined
    | [@bs.as "logo-tux"] `undefined
    | [@bs.as "logo-twitch"] `undefined
    | [@bs.as "logo-twitter"] `undefined
    | [@bs.as "logo-usd"] `undefined
    | [@bs.as "logo-vimeo"] `undefined
    | [@bs.as "logo-vk"] `undefined
    | [@bs.as "logo-whatsapp"] `undefined
    | [@bs.as "logo-windows"] `undefined
    | [@bs.as "logo-wordpress"] `undefined
    | [@bs.as "logo-xbox"] `undefined
    | [@bs.as "logo-xing"] `undefined
    | [@bs.as "logo-yahoo"] `undefined
    | [@bs.as "logo-yen"] `undefined
    | [@bs.as "logo-youtube"] `undefined
    | [@bs.as "md-add"] `undefined
    | [@bs.as "md-add-circle"] `undefined
    | [@bs.as "md-add-circle-outline"] `undefined
    | [@bs.as "md-airplane"] `undefined
    | [@bs.as "md-alarm"] `undefined
    | [@bs.as "md-albums"] `undefined
    | [@bs.as "md-alert"] `undefined
    | [@bs.as "md-american-football"] `undefined
    | [@bs.as "md-analytics"] `undefined
    | [@bs.as "md-aperture"] `undefined
    | [@bs.as "md-apps"] `undefined
    | [@bs.as "md-appstore"] `undefined
    | [@bs.as "md-archive"] `undefined
    | [@bs.as "md-arrow-back"] `undefined
    | [@bs.as "md-arrow-down"] `undefined
    | [@bs.as "md-arrow-dropdown"] `undefined
    | [@bs.as "md-arrow-dropdown-circle"] `undefined
    | [@bs.as "md-arrow-dropleft"] `undefined
    | [@bs.as "md-arrow-dropleft-circle"] `undefined
    | [@bs.as "md-arrow-dropright"] `undefined
    | [@bs.as "md-arrow-dropright-circle"] `undefined
    | [@bs.as "md-arrow-dropup"] `undefined
    | [@bs.as "md-arrow-dropup-circle"] `undefined
    | [@bs.as "md-arrow-forward"] `undefined
    | [@bs.as "md-arrow-round-back"] `undefined
    | [@bs.as "md-arrow-round-down"] `undefined
    | [@bs.as "md-arrow-round-forward"] `undefined
    | [@bs.as "md-arrow-round-up"] `undefined
    | [@bs.as "md-arrow-up"] `undefined
    | [@bs.as "md-at"] `undefined
    | [@bs.as "md-attach"] `undefined
    | [@bs.as "md-backspace"] `undefined
    | [@bs.as "md-barcode"] `undefined
    | [@bs.as "md-baseball"] `undefined
    | [@bs.as "md-basket"] `undefined
    | [@bs.as "md-basketball"] `undefined
    | [@bs.as "md-battery-charging"] `undefined
    | [@bs.as "md-battery-dead"] `undefined
    | [@bs.as "md-battery-full"] `undefined
    | [@bs.as "md-beaker"] `undefined
    | [@bs.as "md-bed"] `undefined
    | [@bs.as "md-beer"] `undefined
    | [@bs.as "md-bicycle"] `undefined
    | [@bs.as "md-bluetooth"] `undefined
    | [@bs.as "md-boat"] `undefined
    | [@bs.as "md-body"] `undefined
    | [@bs.as "md-bonfire"] `undefined
    | [@bs.as "md-book"] `undefined
    | [@bs.as "md-bookmark"] `undefined
    | [@bs.as "md-bookmarks"] `undefined
    | [@bs.as "md-bowtie"] `undefined
    | [@bs.as "md-briefcase"] `undefined
    | [@bs.as "md-browsers"] `undefined
    | [@bs.as "md-brush"] `undefined
    | [@bs.as "md-bug"] `undefined
    | [@bs.as "md-build"] `undefined
    | [@bs.as "md-bulb"] `undefined
    | [@bs.as "md-bus"] `undefined
    | [@bs.as "md-business"] `undefined
    | [@bs.as "md-cafe"] `undefined
    | [@bs.as "md-calculator"] `undefined
    | [@bs.as "md-calendar"] `undefined
    | [@bs.as "md-call"] `undefined
    | [@bs.as "md-camera"] `undefined
    | [@bs.as "md-car"] `undefined
    | [@bs.as "md-card"] `undefined
    | [@bs.as "md-cart"] `undefined
    | [@bs.as "md-cash"] `undefined
    | [@bs.as "md-cellular"] `undefined
    | [@bs.as "md-chatboxes"] `undefined
    | [@bs.as "md-chatbubbles"] `undefined
    | [@bs.as "md-checkbox"] `undefined
    | [@bs.as "md-checkbox-outline"] `undefined
    | [@bs.as "md-checkmark"] `undefined
    | [@bs.as "md-checkmark-circle"] `undefined
    | [@bs.as "md-checkmark-circle-outline"] `undefined
    | [@bs.as "md-clipboard"] `undefined
    | [@bs.as "md-clock"] `undefined
    | [@bs.as "md-close"] `undefined
    | [@bs.as "md-close-circle"] `undefined
    | [@bs.as "md-close-circle-outline"] `undefined
    | [@bs.as "md-cloud"] `undefined
    | [@bs.as "md-cloud-circle"] `undefined
    | [@bs.as "md-cloud-done"] `undefined
    | [@bs.as "md-cloud-download"] `undefined
    | [@bs.as "md-cloud-outline"] `undefined
    | [@bs.as "md-cloud-upload"] `undefined
    | [@bs.as "md-cloudy"] `undefined
    | [@bs.as "md-cloudy-night"] `undefined
    | [@bs.as "md-code"] `undefined
    | [@bs.as "md-code-download"] `undefined
    | [@bs.as "md-code-working"] `undefined
    | [@bs.as "md-cog"] `undefined
    | [@bs.as "md-color-fill"] `undefined
    | [@bs.as "md-color-filter"] `undefined
    | [@bs.as "md-color-palette"] `undefined
    | [@bs.as "md-color-wand"] `undefined
    | [@bs.as "md-compass"] `undefined
    | [@bs.as "md-construct"] `undefined
    | [@bs.as "md-contact"] `undefined
    | [@bs.as "md-contacts"] `undefined
    | [@bs.as "md-contract"] `undefined
    | [@bs.as "md-contrast"] `undefined
    | [@bs.as "md-copy"] `undefined
    | [@bs.as "md-create"] `undefined
    | [@bs.as "md-crop"] `undefined
    | [@bs.as "md-cube"] `undefined
    | [@bs.as "md-cut"] `undefined
    | [@bs.as "md-desktop"] `undefined
    | [@bs.as "md-disc"] `undefined
    | [@bs.as "md-document"] `undefined
    | [@bs.as "md-done-all"] `undefined
    | [@bs.as "md-download"] `undefined
    | [@bs.as "md-easel"] `undefined
    | [@bs.as "md-egg"] `undefined
    | [@bs.as "md-exit"] `undefined
    | [@bs.as "md-expand"] `undefined
    | [@bs.as "md-eye"] `undefined
    | [@bs.as "md-eye-off"] `undefined
    | [@bs.as "md-fastforward"] `undefined
    | [@bs.as "md-female"] `undefined
    | [@bs.as "md-filing"] `undefined
    | [@bs.as "md-film"] `undefined
    | [@bs.as "md-finger-print"] `undefined
    | [@bs.as "md-fitness"] `undefined
    | [@bs.as "md-flag"] `undefined
    | [@bs.as "md-flame"] `undefined
    | [@bs.as "md-flash"] `undefined
    | [@bs.as "md-flash-off"] `undefined
    | [@bs.as "md-flashlight"] `undefined
    | [@bs.as "md-flask"] `undefined
    | [@bs.as "md-flower"] `undefined
    | [@bs.as "md-folder"] `undefined
    | [@bs.as "md-folder-open"] `undefined
    | [@bs.as "md-football"] `undefined
    | [@bs.as "md-funnel"] `undefined
    | [@bs.as "md-gift"] `undefined
    | [@bs.as "md-git-branch"] `undefined
    | [@bs.as "md-git-commit"] `undefined
    | [@bs.as "md-git-compare"] `undefined
    | [@bs.as "md-git-merge"] `undefined
    | [@bs.as "md-git-network"] `undefined
    | [@bs.as "md-git-pull-request"] `undefined
    | [@bs.as "md-glasses"] `undefined
    | [@bs.as "md-globe"] `undefined
    | [@bs.as "md-grid"] `undefined
    | [@bs.as "md-hammer"] `undefined
    | [@bs.as "md-hand"] `undefined
    | [@bs.as "md-happy"] `undefined
    | [@bs.as "md-headset"] `undefined
    | [@bs.as "md-heart"] `undefined
    | [@bs.as "md-heart-dislike"] `undefined
    | [@bs.as "md-heart-empty"] `undefined
    | [@bs.as "md-heart-half"] `undefined
    | [@bs.as "md-help"] `undefined
    | [@bs.as "md-help-buoy"] `undefined
    | [@bs.as "md-help-circle"] `undefined
    | [@bs.as "md-help-circle-outline"] `undefined
    | [@bs.as "md-home"] `undefined
    | [@bs.as "md-hourglass"] `undefined
    | [@bs.as "md-ice-cream"] `undefined
    | [@bs.as "md-image"] `undefined
    | [@bs.as "md-images"] `undefined
    | [@bs.as "md-infinite"] `undefined
    | [@bs.as "md-information"] `undefined
    | [@bs.as "md-information-circle"] `undefined
    | [@bs.as "md-information-circle-outline"] `undefined
    | [@bs.as "md-jet"] `undefined
    | [@bs.as "md-journal"] `undefined
    | [@bs.as "md-key"] `undefined
    | [@bs.as "md-keypad"] `undefined
    | [@bs.as "md-laptop"] `undefined
    | [@bs.as "md-leaf"] `undefined
    | [@bs.as "md-link"] `undefined
    | [@bs.as "md-list"] `undefined
    | [@bs.as "md-list-box"] `undefined
    | [@bs.as "md-locate"] `undefined
    | [@bs.as "md-lock"] `undefined
    | [@bs.as "md-log-in"] `undefined
    | [@bs.as "md-log-out"] `undefined
    | [@bs.as "md-magnet"] `undefined
    | [@bs.as "md-mail"] `undefined
    | [@bs.as "md-mail-open"] `undefined
    | [@bs.as "md-mail-unread"] `undefined
    | [@bs.as "md-male"] `undefined
    | [@bs.as "md-man"] `undefined
    | [@bs.as "md-map"] `undefined
    | [@bs.as "md-medal"] `undefined
    | [@bs.as "md-medical"] `undefined
    | [@bs.as "md-medkit"] `undefined
    | [@bs.as "md-megaphone"] `undefined
    | [@bs.as "md-menu"] `undefined
    | [@bs.as "md-mic"] `undefined
    | [@bs.as "md-mic-off"] `undefined
    | [@bs.as "md-microphone"] `undefined
    | [@bs.as "md-moon"] `undefined
    | [@bs.as "md-more"] `undefined
    | [@bs.as "md-move"] `undefined
    | [@bs.as "md-musical-note"] `undefined
    | [@bs.as "md-musical-notes"] `undefined
    | [@bs.as "md-navigate"] `undefined
    | [@bs.as "md-notifications"] `undefined
    | [@bs.as "md-notifications-off"] `undefined
    | [@bs.as "md-notifications-outline"] `undefined
    | [@bs.as "md-nuclear"] `undefined
    | [@bs.as "md-nutrition"] `undefined
    | [@bs.as "md-open"] `undefined
    | [@bs.as "md-options"] `undefined
    | [@bs.as "md-outlet"] `undefined
    | [@bs.as "md-paper"] `undefined
    | [@bs.as "md-paper-plane"] `undefined
    | [@bs.as "md-partly-sunny"] `undefined
    | [@bs.as "md-pause"] `undefined
    | [@bs.as "md-paw"] `undefined
    | [@bs.as "md-people"] `undefined
    | [@bs.as "md-person"] `undefined
    | [@bs.as "md-person-add"] `undefined
    | [@bs.as "md-phone-landscape"] `undefined
    | [@bs.as "md-phone-portrait"] `undefined
    | [@bs.as "md-photos"] `undefined
    | [@bs.as "md-pie"] `undefined
    | [@bs.as "md-pin"] `undefined
    | [@bs.as "md-pint"] `undefined
    | [@bs.as "md-pizza"] `undefined
    | [@bs.as "md-planet"] `undefined
    | [@bs.as "md-play"] `undefined
    | [@bs.as "md-play-circle"] `undefined
    | [@bs.as "md-podium"] `undefined
    | [@bs.as "md-power"] `undefined
    | [@bs.as "md-pricetag"] `undefined
    | [@bs.as "md-pricetags"] `undefined
    | [@bs.as "md-print"] `undefined
    | [@bs.as "md-pulse"] `undefined
    | [@bs.as "md-qr-scanner"] `undefined
    | [@bs.as "md-quote"] `undefined
    | [@bs.as "md-radio"] `undefined
    | [@bs.as "md-radio-button-off"] `undefined
    | [@bs.as "md-radio-button-on"] `undefined
    | [@bs.as "md-rainy"] `undefined
    | [@bs.as "md-recording"] `undefined
    | [@bs.as "md-redo"] `undefined
    | [@bs.as "md-refresh"] `undefined
    | [@bs.as "md-refresh-circle"] `undefined
    | [@bs.as "md-remove"] `undefined
    | [@bs.as "md-remove-circle"] `undefined
    | [@bs.as "md-remove-circle-outline"] `undefined
    | [@bs.as "md-reorder"] `undefined
    | [@bs.as "md-repeat"] `undefined
    | [@bs.as "md-resize"] `undefined
    | [@bs.as "md-restaurant"] `undefined
    | [@bs.as "md-return-left"] `undefined
    | [@bs.as "md-return-right"] `undefined
    | [@bs.as "md-reverse-camera"] `undefined
    | [@bs.as "md-rewind"] `undefined
    | [@bs.as "md-ribbon"] `undefined
    | [@bs.as "md-rocket"] `undefined
    | [@bs.as "md-rose"] `undefined
    | [@bs.as "md-sad"] `undefined
    | [@bs.as "md-save"] `undefined
    | [@bs.as "md-school"] `undefined
    | [@bs.as "md-search"] `undefined
    | [@bs.as "md-send"] `undefined
    | [@bs.as "md-settings"] `undefined
    | [@bs.as "md-share"] `undefined
    | [@bs.as "md-share-alt"] `undefined
    | [@bs.as "md-shirt"] `undefined
    | [@bs.as "md-shuffle"] `undefined
    | [@bs.as "md-skip-backward"] `undefined
    | [@bs.as "md-skip-forward"] `undefined
    | [@bs.as "md-snow"] `undefined
    | [@bs.as "md-speedometer"] `undefined
    | [@bs.as "md-square"] `undefined
    | [@bs.as "md-square-outline"] `undefined
    | [@bs.as "md-star"] `undefined
    | [@bs.as "md-star-half"] `undefined
    | [@bs.as "md-star-outline"] `undefined
    | [@bs.as "md-stats"] `undefined
    | [@bs.as "md-stopwatch"] `undefined
    | [@bs.as "md-subway"] `undefined
    | [@bs.as "md-sunny"] `undefined
    | [@bs.as "md-swap"] `undefined
    | [@bs.as "md-switch"] `undefined
    | [@bs.as "md-sync"] `undefined
    | [@bs.as "md-tablet-landscape"] `undefined
    | [@bs.as "md-tablet-portrait"] `undefined
    | [@bs.as "md-tennisball"] `undefined
    | [@bs.as "md-text"] `undefined
    | [@bs.as "md-thermometer"] `undefined
    | [@bs.as "md-thumbs-down"] `undefined
    | [@bs.as "md-thumbs-up"] `undefined
    | [@bs.as "md-thunderstorm"] `undefined
    | [@bs.as "md-time"] `undefined
    | [@bs.as "md-timer"] `undefined
    | [@bs.as "md-today"] `undefined
    | [@bs.as "md-train"] `undefined
    | [@bs.as "md-transgender"] `undefined
    | [@bs.as "md-trash"] `undefined
    | [@bs.as "md-trending-down"] `undefined
    | [@bs.as "md-trending-up"] `undefined
    | [@bs.as "md-trophy"] `undefined
    | [@bs.as "md-tv"] `undefined
    | [@bs.as "md-umbrella"] `undefined
    | [@bs.as "md-undo"] `undefined
    | [@bs.as "md-unlock"] `undefined
    | [@bs.as "md-videocam"] `undefined
    | [@bs.as "md-volume-high"] `undefined
    | [@bs.as "md-volume-low"] `undefined
    | [@bs.as "md-volume-mute"] `undefined
    | [@bs.as "md-volume-off"] `undefined
    | [@bs.as "md-walk"] `undefined
    | [@bs.as "md-wallet"] `undefined
    | [@bs.as "md-warning"] `undefined
    | [@bs.as "md-watch"] `undefined
    | [@bs.as "md-water"] `undefined
    | [@bs.as "md-wifi"] `undefined
    | [@bs.as "md-wine"] `undefined
    | [@bs.as "md-woman"] `undefined
  ]
  let nameToJs = nameToJs;

  [@bs.deriving abstract]
  type props = {
    [@bs.optional]
    allowFontScaling: bool,
    [@bs.optional]
    name: name,
    [@bs.optional]
    size: int,
    [@bs.optional]
    color: string,
    [@bs.optional]
    style: BsReactNative.Style.t,
  };

  let make =
    (
      ~allowFontScaling=false,
      ~name=`undefined,
      ~color="black",
      ~size=12,
      ~style=BsReactNative.Style.style([]),
      children,
    ) =>
  ReasonReact.wrapJsForReason(
    ~reactClass=js,
    ~props=
      props(
        ~allowFontScaling,
        ~name,
        ~size,
        ~color,
        ~style,
        (),
      ),
    children,
  );

}