// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var VectorIcons = require("@expo/vector-icons");
var Style$BsReactNative = require("bs-react-native/src/style.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    487210640,
    "ios-add"
  ],
  /* tuple */[
    487210640,
    "ios-add-circle"
  ],
  /* tuple */[
    487210640,
    "ios-add-circle-outline"
  ],
  /* tuple */[
    487210640,
    "ios-airplane"
  ],
  /* tuple */[
    487210640,
    "ios-alarm"
  ],
  /* tuple */[
    487210640,
    "ios-albums"
  ],
  /* tuple */[
    487210640,
    "ios-alert"
  ],
  /* tuple */[
    487210640,
    "ios-american-football"
  ],
  /* tuple */[
    487210640,
    "ios-analytics"
  ],
  /* tuple */[
    487210640,
    "ios-aperture"
  ],
  /* tuple */[
    487210640,
    "ios-apps"
  ],
  /* tuple */[
    487210640,
    "ios-appstore"
  ],
  /* tuple */[
    487210640,
    "ios-archive"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-back"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-down"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropdown"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropdown-circle"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropleft"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropleft-circle"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropright"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropright-circle"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropup"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-dropup-circle"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-forward"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-round-back"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-round-down"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-round-forward"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-round-up"
  ],
  /* tuple */[
    487210640,
    "ios-arrow-up"
  ],
  /* tuple */[
    487210640,
    "ios-at"
  ],
  /* tuple */[
    487210640,
    "ios-attach"
  ],
  /* tuple */[
    487210640,
    "ios-backspace"
  ],
  /* tuple */[
    487210640,
    "ios-barcode"
  ],
  /* tuple */[
    487210640,
    "ios-baseball"
  ],
  /* tuple */[
    487210640,
    "ios-basket"
  ],
  /* tuple */[
    487210640,
    "ios-basketball"
  ],
  /* tuple */[
    487210640,
    "ios-battery-charging"
  ],
  /* tuple */[
    487210640,
    "ios-battery-dead"
  ],
  /* tuple */[
    487210640,
    "ios-battery-full"
  ],
  /* tuple */[
    487210640,
    "ios-beaker"
  ],
  /* tuple */[
    487210640,
    "ios-bed"
  ],
  /* tuple */[
    487210640,
    "ios-beer"
  ],
  /* tuple */[
    487210640,
    "ios-bicycle"
  ],
  /* tuple */[
    487210640,
    "ios-bluetooth"
  ],
  /* tuple */[
    487210640,
    "ios-boat"
  ],
  /* tuple */[
    487210640,
    "ios-body"
  ],
  /* tuple */[
    487210640,
    "ios-bonfire"
  ],
  /* tuple */[
    487210640,
    "ios-book"
  ],
  /* tuple */[
    487210640,
    "ios-bookmark"
  ],
  /* tuple */[
    487210640,
    "ios-bookmarks"
  ],
  /* tuple */[
    487210640,
    "ios-bowtie"
  ],
  /* tuple */[
    487210640,
    "ios-briefcase"
  ],
  /* tuple */[
    487210640,
    "ios-browsers"
  ],
  /* tuple */[
    487210640,
    "ios-brush"
  ],
  /* tuple */[
    487210640,
    "ios-bug"
  ],
  /* tuple */[
    487210640,
    "ios-build"
  ],
  /* tuple */[
    487210640,
    "ios-bulb"
  ],
  /* tuple */[
    487210640,
    "ios-bus"
  ],
  /* tuple */[
    487210640,
    "ios-business"
  ],
  /* tuple */[
    487210640,
    "ios-cafe"
  ],
  /* tuple */[
    487210640,
    "ios-calculator"
  ],
  /* tuple */[
    487210640,
    "ios-calendar"
  ],
  /* tuple */[
    487210640,
    "ios-call"
  ],
  /* tuple */[
    487210640,
    "ios-camera"
  ],
  /* tuple */[
    487210640,
    "ios-car"
  ],
  /* tuple */[
    487210640,
    "ios-card"
  ],
  /* tuple */[
    487210640,
    "ios-cart"
  ],
  /* tuple */[
    487210640,
    "ios-cash"
  ],
  /* tuple */[
    487210640,
    "ios-cellular"
  ],
  /* tuple */[
    487210640,
    "ios-chatboxes"
  ],
  /* tuple */[
    487210640,
    "ios-chatbubbles"
  ],
  /* tuple */[
    487210640,
    "ios-checkbox"
  ],
  /* tuple */[
    487210640,
    "ios-checkbox-outline"
  ],
  /* tuple */[
    487210640,
    "ios-checkmark"
  ],
  /* tuple */[
    487210640,
    "ios-checkmark-circle"
  ],
  /* tuple */[
    487210640,
    "ios-checkmark-circle-outline"
  ],
  /* tuple */[
    487210640,
    "ios-clipboard"
  ],
  /* tuple */[
    487210640,
    "ios-clock"
  ],
  /* tuple */[
    487210640,
    "ios-close"
  ],
  /* tuple */[
    487210640,
    "ios-close-circle"
  ],
  /* tuple */[
    487210640,
    "ios-close-circle-outline"
  ],
  /* tuple */[
    487210640,
    "ios-cloud"
  ],
  /* tuple */[
    487210640,
    "ios-cloud-circle"
  ],
  /* tuple */[
    487210640,
    "ios-cloud-done"
  ],
  /* tuple */[
    487210640,
    "ios-cloud-download"
  ],
  /* tuple */[
    487210640,
    "ios-cloud-outline"
  ],
  /* tuple */[
    487210640,
    "ios-cloud-upload"
  ],
  /* tuple */[
    487210640,
    "ios-cloudy"
  ],
  /* tuple */[
    487210640,
    "ios-cloudy-night"
  ],
  /* tuple */[
    487210640,
    "ios-code"
  ],
  /* tuple */[
    487210640,
    "ios-code-download"
  ],
  /* tuple */[
    487210640,
    "ios-code-working"
  ],
  /* tuple */[
    487210640,
    "ios-cog"
  ],
  /* tuple */[
    487210640,
    "ios-color-fill"
  ],
  /* tuple */[
    487210640,
    "ios-color-filter"
  ],
  /* tuple */[
    487210640,
    "ios-color-palette"
  ],
  /* tuple */[
    487210640,
    "ios-color-wand"
  ],
  /* tuple */[
    487210640,
    "ios-compass"
  ],
  /* tuple */[
    487210640,
    "ios-construct"
  ],
  /* tuple */[
    487210640,
    "ios-contact"
  ],
  /* tuple */[
    487210640,
    "ios-contacts"
  ],
  /* tuple */[
    487210640,
    "ios-contract"
  ],
  /* tuple */[
    487210640,
    "ios-contrast"
  ],
  /* tuple */[
    487210640,
    "ios-copy"
  ],
  /* tuple */[
    487210640,
    "ios-create"
  ],
  /* tuple */[
    487210640,
    "ios-crop"
  ],
  /* tuple */[
    487210640,
    "ios-cube"
  ],
  /* tuple */[
    487210640,
    "ios-cut"
  ],
  /* tuple */[
    487210640,
    "ios-desktop"
  ],
  /* tuple */[
    487210640,
    "ios-disc"
  ],
  /* tuple */[
    487210640,
    "ios-document"
  ],
  /* tuple */[
    487210640,
    "ios-done-all"
  ],
  /* tuple */[
    487210640,
    "ios-download"
  ],
  /* tuple */[
    487210640,
    "ios-easel"
  ],
  /* tuple */[
    487210640,
    "ios-egg"
  ],
  /* tuple */[
    487210640,
    "ios-exit"
  ],
  /* tuple */[
    487210640,
    "ios-expand"
  ],
  /* tuple */[
    487210640,
    "ios-eye"
  ],
  /* tuple */[
    487210640,
    "ios-eye-off"
  ],
  /* tuple */[
    487210640,
    "ios-fastforward"
  ],
  /* tuple */[
    487210640,
    "ios-female"
  ],
  /* tuple */[
    487210640,
    "ios-filing"
  ],
  /* tuple */[
    487210640,
    "ios-film"
  ],
  /* tuple */[
    487210640,
    "ios-finger-print"
  ],
  /* tuple */[
    487210640,
    "ios-fitness"
  ],
  /* tuple */[
    487210640,
    "ios-flag"
  ],
  /* tuple */[
    487210640,
    "ios-flame"
  ],
  /* tuple */[
    487210640,
    "ios-flash"
  ],
  /* tuple */[
    487210640,
    "ios-flash-off"
  ],
  /* tuple */[
    487210640,
    "ios-flashlight"
  ],
  /* tuple */[
    487210640,
    "ios-flask"
  ],
  /* tuple */[
    487210640,
    "ios-flower"
  ],
  /* tuple */[
    487210640,
    "ios-folder"
  ],
  /* tuple */[
    487210640,
    "ios-folder-open"
  ],
  /* tuple */[
    487210640,
    "ios-football"
  ],
  /* tuple */[
    487210640,
    "ios-funnel"
  ],
  /* tuple */[
    487210640,
    "ios-gift"
  ],
  /* tuple */[
    487210640,
    "ios-git-branch"
  ],
  /* tuple */[
    487210640,
    "ios-git-commit"
  ],
  /* tuple */[
    487210640,
    "ios-git-compare"
  ],
  /* tuple */[
    487210640,
    "ios-git-merge"
  ],
  /* tuple */[
    487210640,
    "ios-git-network"
  ],
  /* tuple */[
    487210640,
    "ios-git-pull-request"
  ],
  /* tuple */[
    487210640,
    "ios-glasses"
  ],
  /* tuple */[
    487210640,
    "ios-globe"
  ],
  /* tuple */[
    487210640,
    "ios-grid"
  ],
  /* tuple */[
    487210640,
    "ios-hammer"
  ],
  /* tuple */[
    487210640,
    "ios-hand"
  ],
  /* tuple */[
    487210640,
    "ios-happy"
  ],
  /* tuple */[
    487210640,
    "ios-headset"
  ],
  /* tuple */[
    487210640,
    "ios-heart"
  ],
  /* tuple */[
    487210640,
    "ios-heart-dislike"
  ],
  /* tuple */[
    487210640,
    "ios-heart-empty"
  ],
  /* tuple */[
    487210640,
    "ios-heart-half"
  ],
  /* tuple */[
    487210640,
    "ios-help"
  ],
  /* tuple */[
    487210640,
    "ios-help-buoy"
  ],
  /* tuple */[
    487210640,
    "ios-help-circle"
  ],
  /* tuple */[
    487210640,
    "ios-help-circle-outline"
  ],
  /* tuple */[
    487210640,
    "ios-home"
  ],
  /* tuple */[
    487210640,
    "ios-hourglass"
  ],
  /* tuple */[
    487210640,
    "ios-ice-cream"
  ],
  /* tuple */[
    487210640,
    "ios-image"
  ],
  /* tuple */[
    487210640,
    "ios-images"
  ],
  /* tuple */[
    487210640,
    "ios-infinite"
  ],
  /* tuple */[
    487210640,
    "ios-information"
  ],
  /* tuple */[
    487210640,
    "ios-information-circle"
  ],
  /* tuple */[
    487210640,
    "ios-information-circle-outline"
  ],
  /* tuple */[
    487210640,
    "ios-jet"
  ],
  /* tuple */[
    487210640,
    "ios-journal"
  ],
  /* tuple */[
    487210640,
    "ios-key"
  ],
  /* tuple */[
    487210640,
    "ios-keypad"
  ],
  /* tuple */[
    487210640,
    "ios-laptop"
  ],
  /* tuple */[
    487210640,
    "ios-leaf"
  ],
  /* tuple */[
    487210640,
    "ios-link"
  ],
  /* tuple */[
    487210640,
    "ios-list"
  ],
  /* tuple */[
    487210640,
    "ios-list-box"
  ],
  /* tuple */[
    487210640,
    "ios-locate"
  ],
  /* tuple */[
    487210640,
    "ios-lock"
  ],
  /* tuple */[
    487210640,
    "ios-log-in"
  ],
  /* tuple */[
    487210640,
    "ios-log-out"
  ],
  /* tuple */[
    487210640,
    "ios-magnet"
  ],
  /* tuple */[
    487210640,
    "ios-mail"
  ],
  /* tuple */[
    487210640,
    "ios-mail-open"
  ],
  /* tuple */[
    487210640,
    "ios-mail-unread"
  ],
  /* tuple */[
    487210640,
    "ios-male"
  ],
  /* tuple */[
    487210640,
    "ios-man"
  ],
  /* tuple */[
    487210640,
    "ios-map"
  ],
  /* tuple */[
    487210640,
    "ios-medal"
  ],
  /* tuple */[
    487210640,
    "ios-medical"
  ],
  /* tuple */[
    487210640,
    "ios-medkit"
  ],
  /* tuple */[
    487210640,
    "ios-megaphone"
  ],
  /* tuple */[
    487210640,
    "ios-menu"
  ],
  /* tuple */[
    487210640,
    "ios-mic"
  ],
  /* tuple */[
    487210640,
    "ios-mic-off"
  ],
  /* tuple */[
    487210640,
    "ios-microphone"
  ],
  /* tuple */[
    487210640,
    "ios-moon"
  ],
  /* tuple */[
    487210640,
    "ios-more"
  ],
  /* tuple */[
    487210640,
    "ios-move"
  ],
  /* tuple */[
    487210640,
    "ios-musical-note"
  ],
  /* tuple */[
    487210640,
    "ios-musical-notes"
  ],
  /* tuple */[
    487210640,
    "ios-navigate"
  ],
  /* tuple */[
    487210640,
    "ios-notifications"
  ],
  /* tuple */[
    487210640,
    "ios-notifications-off"
  ],
  /* tuple */[
    487210640,
    "ios-notifications-outline"
  ],
  /* tuple */[
    487210640,
    "ios-nuclear"
  ],
  /* tuple */[
    487210640,
    "ios-nutrition"
  ],
  /* tuple */[
    487210640,
    "ios-open"
  ],
  /* tuple */[
    487210640,
    "ios-options"
  ],
  /* tuple */[
    487210640,
    "ios-outlet"
  ],
  /* tuple */[
    487210640,
    "ios-paper"
  ],
  /* tuple */[
    487210640,
    "ios-paper-plane"
  ],
  /* tuple */[
    487210640,
    "ios-partly-sunny"
  ],
  /* tuple */[
    487210640,
    "ios-pause"
  ],
  /* tuple */[
    487210640,
    "ios-paw"
  ],
  /* tuple */[
    487210640,
    "ios-people"
  ],
  /* tuple */[
    487210640,
    "ios-person"
  ],
  /* tuple */[
    487210640,
    "ios-person-add"
  ],
  /* tuple */[
    487210640,
    "ios-phone-landscape"
  ],
  /* tuple */[
    487210640,
    "ios-phone-portrait"
  ],
  /* tuple */[
    487210640,
    "ios-photos"
  ],
  /* tuple */[
    487210640,
    "ios-pie"
  ],
  /* tuple */[
    487210640,
    "ios-pin"
  ],
  /* tuple */[
    487210640,
    "ios-pint"
  ],
  /* tuple */[
    487210640,
    "ios-pizza"
  ],
  /* tuple */[
    487210640,
    "ios-planet"
  ],
  /* tuple */[
    487210640,
    "ios-play"
  ],
  /* tuple */[
    487210640,
    "ios-play-circle"
  ],
  /* tuple */[
    487210640,
    "ios-podium"
  ],
  /* tuple */[
    487210640,
    "ios-power"
  ],
  /* tuple */[
    487210640,
    "ios-pricetag"
  ],
  /* tuple */[
    487210640,
    "ios-pricetags"
  ],
  /* tuple */[
    487210640,
    "ios-print"
  ],
  /* tuple */[
    487210640,
    "ios-pulse"
  ],
  /* tuple */[
    487210640,
    "ios-qr-scanner"
  ],
  /* tuple */[
    487210640,
    "ios-quote"
  ],
  /* tuple */[
    487210640,
    "ios-radio"
  ],
  /* tuple */[
    487210640,
    "ios-radio-button-off"
  ],
  /* tuple */[
    487210640,
    "ios-radio-button-on"
  ],
  /* tuple */[
    487210640,
    "ios-rainy"
  ],
  /* tuple */[
    487210640,
    "ios-recording"
  ],
  /* tuple */[
    487210640,
    "ios-redo"
  ],
  /* tuple */[
    487210640,
    "ios-refresh"
  ],
  /* tuple */[
    487210640,
    "ios-refresh-circle"
  ],
  /* tuple */[
    487210640,
    "ios-remove"
  ],
  /* tuple */[
    487210640,
    "ios-remove-circle"
  ],
  /* tuple */[
    487210640,
    "ios-remove-circle-outline"
  ],
  /* tuple */[
    487210640,
    "ios-reorder"
  ],
  /* tuple */[
    487210640,
    "ios-repeat"
  ],
  /* tuple */[
    487210640,
    "ios-resize"
  ],
  /* tuple */[
    487210640,
    "ios-restaurant"
  ],
  /* tuple */[
    487210640,
    "ios-return-left"
  ],
  /* tuple */[
    487210640,
    "ios-return-right"
  ],
  /* tuple */[
    487210640,
    "ios-reverse-camera"
  ],
  /* tuple */[
    487210640,
    "ios-rewind"
  ],
  /* tuple */[
    487210640,
    "ios-ribbon"
  ],
  /* tuple */[
    487210640,
    "ios-rocket"
  ],
  /* tuple */[
    487210640,
    "ios-rose"
  ],
  /* tuple */[
    487210640,
    "ios-sad"
  ],
  /* tuple */[
    487210640,
    "ios-save"
  ],
  /* tuple */[
    487210640,
    "ios-school"
  ],
  /* tuple */[
    487210640,
    "ios-search"
  ],
  /* tuple */[
    487210640,
    "ios-send"
  ],
  /* tuple */[
    487210640,
    "ios-settings"
  ],
  /* tuple */[
    487210640,
    "ios-share"
  ],
  /* tuple */[
    487210640,
    "ios-share-alt"
  ],
  /* tuple */[
    487210640,
    "ios-shirt"
  ],
  /* tuple */[
    487210640,
    "ios-shuffle"
  ],
  /* tuple */[
    487210640,
    "ios-skip-backward"
  ],
  /* tuple */[
    487210640,
    "ios-skip-forward"
  ],
  /* tuple */[
    487210640,
    "ios-snow"
  ],
  /* tuple */[
    487210640,
    "ios-speedometer"
  ],
  /* tuple */[
    487210640,
    "ios-square"
  ],
  /* tuple */[
    487210640,
    "ios-square-outline"
  ],
  /* tuple */[
    487210640,
    "ios-star"
  ],
  /* tuple */[
    487210640,
    "ios-star-half"
  ],
  /* tuple */[
    487210640,
    "ios-star-outline"
  ],
  /* tuple */[
    487210640,
    "ios-stats"
  ],
  /* tuple */[
    487210640,
    "ios-stopwatch"
  ],
  /* tuple */[
    487210640,
    "ios-subway"
  ],
  /* tuple */[
    487210640,
    "ios-sunny"
  ],
  /* tuple */[
    487210640,
    "ios-swap"
  ],
  /* tuple */[
    487210640,
    "ios-switch"
  ],
  /* tuple */[
    487210640,
    "ios-sync"
  ],
  /* tuple */[
    487210640,
    "ios-tablet-landscape"
  ],
  /* tuple */[
    487210640,
    "ios-tablet-portrait"
  ],
  /* tuple */[
    487210640,
    "ios-tennisball"
  ],
  /* tuple */[
    487210640,
    "ios-text"
  ],
  /* tuple */[
    487210640,
    "ios-thermometer"
  ],
  /* tuple */[
    487210640,
    "ios-thumbs-down"
  ],
  /* tuple */[
    487210640,
    "ios-thumbs-up"
  ],
  /* tuple */[
    487210640,
    "ios-thunderstorm"
  ],
  /* tuple */[
    487210640,
    "ios-time"
  ],
  /* tuple */[
    487210640,
    "ios-timer"
  ],
  /* tuple */[
    487210640,
    "ios-today"
  ],
  /* tuple */[
    487210640,
    "ios-train"
  ],
  /* tuple */[
    487210640,
    "ios-transgender"
  ],
  /* tuple */[
    487210640,
    "ios-trash"
  ],
  /* tuple */[
    487210640,
    "ios-trending-down"
  ],
  /* tuple */[
    487210640,
    "ios-trending-up"
  ],
  /* tuple */[
    487210640,
    "ios-trophy"
  ],
  /* tuple */[
    487210640,
    "ios-tv"
  ],
  /* tuple */[
    487210640,
    "ios-umbrella"
  ],
  /* tuple */[
    487210640,
    "ios-undo"
  ],
  /* tuple */[
    487210640,
    "ios-unlock"
  ],
  /* tuple */[
    487210640,
    "ios-videocam"
  ],
  /* tuple */[
    487210640,
    "ios-volume-high"
  ],
  /* tuple */[
    487210640,
    "ios-volume-low"
  ],
  /* tuple */[
    487210640,
    "ios-volume-mute"
  ],
  /* tuple */[
    487210640,
    "ios-volume-off"
  ],
  /* tuple */[
    487210640,
    "ios-walk"
  ],
  /* tuple */[
    487210640,
    "ios-wallet"
  ],
  /* tuple */[
    487210640,
    "ios-warning"
  ],
  /* tuple */[
    487210640,
    "ios-watch"
  ],
  /* tuple */[
    487210640,
    "ios-water"
  ],
  /* tuple */[
    487210640,
    "ios-wifi"
  ],
  /* tuple */[
    487210640,
    "ios-wine"
  ],
  /* tuple */[
    487210640,
    "ios-woman"
  ],
  /* tuple */[
    487210640,
    "logo-android"
  ],
  /* tuple */[
    487210640,
    "logo-angular"
  ],
  /* tuple */[
    487210640,
    "logo-apple"
  ],
  /* tuple */[
    487210640,
    "logo-bitbucket"
  ],
  /* tuple */[
    487210640,
    "logo-bitcoin"
  ],
  /* tuple */[
    487210640,
    "logo-buffer"
  ],
  /* tuple */[
    487210640,
    "logo-chrome"
  ],
  /* tuple */[
    487210640,
    "logo-closed-captioning"
  ],
  /* tuple */[
    487210640,
    "logo-codepen"
  ],
  /* tuple */[
    487210640,
    "logo-css3"
  ],
  /* tuple */[
    487210640,
    "logo-designernews"
  ],
  /* tuple */[
    487210640,
    "logo-dribbble"
  ],
  /* tuple */[
    487210640,
    "logo-dropbox"
  ],
  /* tuple */[
    487210640,
    "logo-euro"
  ],
  /* tuple */[
    487210640,
    "logo-facebook"
  ],
  /* tuple */[
    487210640,
    "logo-flickr"
  ],
  /* tuple */[
    487210640,
    "logo-foursquare"
  ],
  /* tuple */[
    487210640,
    "logo-freebsd-devil"
  ],
  /* tuple */[
    487210640,
    "logo-game-controller-a"
  ],
  /* tuple */[
    487210640,
    "logo-game-controller-b"
  ],
  /* tuple */[
    487210640,
    "logo-github"
  ],
  /* tuple */[
    487210640,
    "logo-google"
  ],
  /* tuple */[
    487210640,
    "logo-googleplus"
  ],
  /* tuple */[
    487210640,
    "logo-hackernews"
  ],
  /* tuple */[
    487210640,
    "logo-html5"
  ],
  /* tuple */[
    487210640,
    "logo-instagram"
  ],
  /* tuple */[
    487210640,
    "logo-ionic"
  ],
  /* tuple */[
    487210640,
    "logo-ionitron"
  ],
  /* tuple */[
    487210640,
    "logo-javascript"
  ],
  /* tuple */[
    487210640,
    "logo-linkedin"
  ],
  /* tuple */[
    487210640,
    "logo-markdown"
  ],
  /* tuple */[
    487210640,
    "logo-model-s"
  ],
  /* tuple */[
    487210640,
    "logo-no-smoking"
  ],
  /* tuple */[
    487210640,
    "logo-nodejs"
  ],
  /* tuple */[
    487210640,
    "logo-npm"
  ],
  /* tuple */[
    487210640,
    "logo-octocat"
  ],
  /* tuple */[
    487210640,
    "logo-pinterest"
  ],
  /* tuple */[
    487210640,
    "logo-playstation"
  ],
  /* tuple */[
    487210640,
    "logo-polymer"
  ],
  /* tuple */[
    487210640,
    "logo-python"
  ],
  /* tuple */[
    487210640,
    "logo-reddit"
  ],
  /* tuple */[
    487210640,
    "logo-rss"
  ],
  /* tuple */[
    487210640,
    "logo-sass"
  ],
  /* tuple */[
    487210640,
    "logo-skype"
  ],
  /* tuple */[
    487210640,
    "logo-slack"
  ],
  /* tuple */[
    487210640,
    "logo-snapchat"
  ],
  /* tuple */[
    487210640,
    "logo-steam"
  ],
  /* tuple */[
    487210640,
    "logo-tumblr"
  ],
  /* tuple */[
    487210640,
    "logo-tux"
  ],
  /* tuple */[
    487210640,
    "logo-twitch"
  ],
  /* tuple */[
    487210640,
    "logo-twitter"
  ],
  /* tuple */[
    487210640,
    "logo-usd"
  ],
  /* tuple */[
    487210640,
    "logo-vimeo"
  ],
  /* tuple */[
    487210640,
    "logo-vk"
  ],
  /* tuple */[
    487210640,
    "logo-whatsapp"
  ],
  /* tuple */[
    487210640,
    "logo-windows"
  ],
  /* tuple */[
    487210640,
    "logo-wordpress"
  ],
  /* tuple */[
    487210640,
    "logo-xbox"
  ],
  /* tuple */[
    487210640,
    "logo-xing"
  ],
  /* tuple */[
    487210640,
    "logo-yahoo"
  ],
  /* tuple */[
    487210640,
    "logo-yen"
  ],
  /* tuple */[
    487210640,
    "logo-youtube"
  ],
  /* tuple */[
    487210640,
    "md-add"
  ],
  /* tuple */[
    487210640,
    "md-add-circle"
  ],
  /* tuple */[
    487210640,
    "md-add-circle-outline"
  ],
  /* tuple */[
    487210640,
    "md-airplane"
  ],
  /* tuple */[
    487210640,
    "md-alarm"
  ],
  /* tuple */[
    487210640,
    "md-albums"
  ],
  /* tuple */[
    487210640,
    "md-alert"
  ],
  /* tuple */[
    487210640,
    "md-american-football"
  ],
  /* tuple */[
    487210640,
    "md-analytics"
  ],
  /* tuple */[
    487210640,
    "md-aperture"
  ],
  /* tuple */[
    487210640,
    "md-apps"
  ],
  /* tuple */[
    487210640,
    "md-appstore"
  ],
  /* tuple */[
    487210640,
    "md-archive"
  ],
  /* tuple */[
    487210640,
    "md-arrow-back"
  ],
  /* tuple */[
    487210640,
    "md-arrow-down"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropdown"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropdown-circle"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropleft"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropleft-circle"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropright"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropright-circle"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropup"
  ],
  /* tuple */[
    487210640,
    "md-arrow-dropup-circle"
  ],
  /* tuple */[
    487210640,
    "md-arrow-forward"
  ],
  /* tuple */[
    487210640,
    "md-arrow-round-back"
  ],
  /* tuple */[
    487210640,
    "md-arrow-round-down"
  ],
  /* tuple */[
    487210640,
    "md-arrow-round-forward"
  ],
  /* tuple */[
    487210640,
    "md-arrow-round-up"
  ],
  /* tuple */[
    487210640,
    "md-arrow-up"
  ],
  /* tuple */[
    487210640,
    "md-at"
  ],
  /* tuple */[
    487210640,
    "md-attach"
  ],
  /* tuple */[
    487210640,
    "md-backspace"
  ],
  /* tuple */[
    487210640,
    "md-barcode"
  ],
  /* tuple */[
    487210640,
    "md-baseball"
  ],
  /* tuple */[
    487210640,
    "md-basket"
  ],
  /* tuple */[
    487210640,
    "md-basketball"
  ],
  /* tuple */[
    487210640,
    "md-battery-charging"
  ],
  /* tuple */[
    487210640,
    "md-battery-dead"
  ],
  /* tuple */[
    487210640,
    "md-battery-full"
  ],
  /* tuple */[
    487210640,
    "md-beaker"
  ],
  /* tuple */[
    487210640,
    "md-bed"
  ],
  /* tuple */[
    487210640,
    "md-beer"
  ],
  /* tuple */[
    487210640,
    "md-bicycle"
  ],
  /* tuple */[
    487210640,
    "md-bluetooth"
  ],
  /* tuple */[
    487210640,
    "md-boat"
  ],
  /* tuple */[
    487210640,
    "md-body"
  ],
  /* tuple */[
    487210640,
    "md-bonfire"
  ],
  /* tuple */[
    487210640,
    "md-book"
  ],
  /* tuple */[
    487210640,
    "md-bookmark"
  ],
  /* tuple */[
    487210640,
    "md-bookmarks"
  ],
  /* tuple */[
    487210640,
    "md-bowtie"
  ],
  /* tuple */[
    487210640,
    "md-briefcase"
  ],
  /* tuple */[
    487210640,
    "md-browsers"
  ],
  /* tuple */[
    487210640,
    "md-brush"
  ],
  /* tuple */[
    487210640,
    "md-bug"
  ],
  /* tuple */[
    487210640,
    "md-build"
  ],
  /* tuple */[
    487210640,
    "md-bulb"
  ],
  /* tuple */[
    487210640,
    "md-bus"
  ],
  /* tuple */[
    487210640,
    "md-business"
  ],
  /* tuple */[
    487210640,
    "md-cafe"
  ],
  /* tuple */[
    487210640,
    "md-calculator"
  ],
  /* tuple */[
    487210640,
    "md-calendar"
  ],
  /* tuple */[
    487210640,
    "md-call"
  ],
  /* tuple */[
    487210640,
    "md-camera"
  ],
  /* tuple */[
    487210640,
    "md-car"
  ],
  /* tuple */[
    487210640,
    "md-card"
  ],
  /* tuple */[
    487210640,
    "md-cart"
  ],
  /* tuple */[
    487210640,
    "md-cash"
  ],
  /* tuple */[
    487210640,
    "md-cellular"
  ],
  /* tuple */[
    487210640,
    "md-chatboxes"
  ],
  /* tuple */[
    487210640,
    "md-chatbubbles"
  ],
  /* tuple */[
    487210640,
    "md-checkbox"
  ],
  /* tuple */[
    487210640,
    "md-checkbox-outline"
  ],
  /* tuple */[
    487210640,
    "md-checkmark"
  ],
  /* tuple */[
    487210640,
    "md-checkmark-circle"
  ],
  /* tuple */[
    487210640,
    "md-checkmark-circle-outline"
  ],
  /* tuple */[
    487210640,
    "md-clipboard"
  ],
  /* tuple */[
    487210640,
    "md-clock"
  ],
  /* tuple */[
    487210640,
    "md-close"
  ],
  /* tuple */[
    487210640,
    "md-close-circle"
  ],
  /* tuple */[
    487210640,
    "md-close-circle-outline"
  ],
  /* tuple */[
    487210640,
    "md-cloud"
  ],
  /* tuple */[
    487210640,
    "md-cloud-circle"
  ],
  /* tuple */[
    487210640,
    "md-cloud-done"
  ],
  /* tuple */[
    487210640,
    "md-cloud-download"
  ],
  /* tuple */[
    487210640,
    "md-cloud-outline"
  ],
  /* tuple */[
    487210640,
    "md-cloud-upload"
  ],
  /* tuple */[
    487210640,
    "md-cloudy"
  ],
  /* tuple */[
    487210640,
    "md-cloudy-night"
  ],
  /* tuple */[
    487210640,
    "md-code"
  ],
  /* tuple */[
    487210640,
    "md-code-download"
  ],
  /* tuple */[
    487210640,
    "md-code-working"
  ],
  /* tuple */[
    487210640,
    "md-cog"
  ],
  /* tuple */[
    487210640,
    "md-color-fill"
  ],
  /* tuple */[
    487210640,
    "md-color-filter"
  ],
  /* tuple */[
    487210640,
    "md-color-palette"
  ],
  /* tuple */[
    487210640,
    "md-color-wand"
  ],
  /* tuple */[
    487210640,
    "md-compass"
  ],
  /* tuple */[
    487210640,
    "md-construct"
  ],
  /* tuple */[
    487210640,
    "md-contact"
  ],
  /* tuple */[
    487210640,
    "md-contacts"
  ],
  /* tuple */[
    487210640,
    "md-contract"
  ],
  /* tuple */[
    487210640,
    "md-contrast"
  ],
  /* tuple */[
    487210640,
    "md-copy"
  ],
  /* tuple */[
    487210640,
    "md-create"
  ],
  /* tuple */[
    487210640,
    "md-crop"
  ],
  /* tuple */[
    487210640,
    "md-cube"
  ],
  /* tuple */[
    487210640,
    "md-cut"
  ],
  /* tuple */[
    487210640,
    "md-desktop"
  ],
  /* tuple */[
    487210640,
    "md-disc"
  ],
  /* tuple */[
    487210640,
    "md-document"
  ],
  /* tuple */[
    487210640,
    "md-done-all"
  ],
  /* tuple */[
    487210640,
    "md-download"
  ],
  /* tuple */[
    487210640,
    "md-easel"
  ],
  /* tuple */[
    487210640,
    "md-egg"
  ],
  /* tuple */[
    487210640,
    "md-exit"
  ],
  /* tuple */[
    487210640,
    "md-expand"
  ],
  /* tuple */[
    487210640,
    "md-eye"
  ],
  /* tuple */[
    487210640,
    "md-eye-off"
  ],
  /* tuple */[
    487210640,
    "md-fastforward"
  ],
  /* tuple */[
    487210640,
    "md-female"
  ],
  /* tuple */[
    487210640,
    "md-filing"
  ],
  /* tuple */[
    487210640,
    "md-film"
  ],
  /* tuple */[
    487210640,
    "md-finger-print"
  ],
  /* tuple */[
    487210640,
    "md-fitness"
  ],
  /* tuple */[
    487210640,
    "md-flag"
  ],
  /* tuple */[
    487210640,
    "md-flame"
  ],
  /* tuple */[
    487210640,
    "md-flash"
  ],
  /* tuple */[
    487210640,
    "md-flash-off"
  ],
  /* tuple */[
    487210640,
    "md-flashlight"
  ],
  /* tuple */[
    487210640,
    "md-flask"
  ],
  /* tuple */[
    487210640,
    "md-flower"
  ],
  /* tuple */[
    487210640,
    "md-folder"
  ],
  /* tuple */[
    487210640,
    "md-folder-open"
  ],
  /* tuple */[
    487210640,
    "md-football"
  ],
  /* tuple */[
    487210640,
    "md-funnel"
  ],
  /* tuple */[
    487210640,
    "md-gift"
  ],
  /* tuple */[
    487210640,
    "md-git-branch"
  ],
  /* tuple */[
    487210640,
    "md-git-commit"
  ],
  /* tuple */[
    487210640,
    "md-git-compare"
  ],
  /* tuple */[
    487210640,
    "md-git-merge"
  ],
  /* tuple */[
    487210640,
    "md-git-network"
  ],
  /* tuple */[
    487210640,
    "md-git-pull-request"
  ],
  /* tuple */[
    487210640,
    "md-glasses"
  ],
  /* tuple */[
    487210640,
    "md-globe"
  ],
  /* tuple */[
    487210640,
    "md-grid"
  ],
  /* tuple */[
    487210640,
    "md-hammer"
  ],
  /* tuple */[
    487210640,
    "md-hand"
  ],
  /* tuple */[
    487210640,
    "md-happy"
  ],
  /* tuple */[
    487210640,
    "md-headset"
  ],
  /* tuple */[
    487210640,
    "md-heart"
  ],
  /* tuple */[
    487210640,
    "md-heart-dislike"
  ],
  /* tuple */[
    487210640,
    "md-heart-empty"
  ],
  /* tuple */[
    487210640,
    "md-heart-half"
  ],
  /* tuple */[
    487210640,
    "md-help"
  ],
  /* tuple */[
    487210640,
    "md-help-buoy"
  ],
  /* tuple */[
    487210640,
    "md-help-circle"
  ],
  /* tuple */[
    487210640,
    "md-help-circle-outline"
  ],
  /* tuple */[
    487210640,
    "md-home"
  ],
  /* tuple */[
    487210640,
    "md-hourglass"
  ],
  /* tuple */[
    487210640,
    "md-ice-cream"
  ],
  /* tuple */[
    487210640,
    "md-image"
  ],
  /* tuple */[
    487210640,
    "md-images"
  ],
  /* tuple */[
    487210640,
    "md-infinite"
  ],
  /* tuple */[
    487210640,
    "md-information"
  ],
  /* tuple */[
    487210640,
    "md-information-circle"
  ],
  /* tuple */[
    487210640,
    "md-information-circle-outline"
  ],
  /* tuple */[
    487210640,
    "md-jet"
  ],
  /* tuple */[
    487210640,
    "md-journal"
  ],
  /* tuple */[
    487210640,
    "md-key"
  ],
  /* tuple */[
    487210640,
    "md-keypad"
  ],
  /* tuple */[
    487210640,
    "md-laptop"
  ],
  /* tuple */[
    487210640,
    "md-leaf"
  ],
  /* tuple */[
    487210640,
    "md-link"
  ],
  /* tuple */[
    487210640,
    "md-list"
  ],
  /* tuple */[
    487210640,
    "md-list-box"
  ],
  /* tuple */[
    487210640,
    "md-locate"
  ],
  /* tuple */[
    487210640,
    "md-lock"
  ],
  /* tuple */[
    487210640,
    "md-log-in"
  ],
  /* tuple */[
    487210640,
    "md-log-out"
  ],
  /* tuple */[
    487210640,
    "md-magnet"
  ],
  /* tuple */[
    487210640,
    "md-mail"
  ],
  /* tuple */[
    487210640,
    "md-mail-open"
  ],
  /* tuple */[
    487210640,
    "md-mail-unread"
  ],
  /* tuple */[
    487210640,
    "md-male"
  ],
  /* tuple */[
    487210640,
    "md-man"
  ],
  /* tuple */[
    487210640,
    "md-map"
  ],
  /* tuple */[
    487210640,
    "md-medal"
  ],
  /* tuple */[
    487210640,
    "md-medical"
  ],
  /* tuple */[
    487210640,
    "md-medkit"
  ],
  /* tuple */[
    487210640,
    "md-megaphone"
  ],
  /* tuple */[
    487210640,
    "md-menu"
  ],
  /* tuple */[
    487210640,
    "md-mic"
  ],
  /* tuple */[
    487210640,
    "md-mic-off"
  ],
  /* tuple */[
    487210640,
    "md-microphone"
  ],
  /* tuple */[
    487210640,
    "md-moon"
  ],
  /* tuple */[
    487210640,
    "md-more"
  ],
  /* tuple */[
    487210640,
    "md-move"
  ],
  /* tuple */[
    487210640,
    "md-musical-note"
  ],
  /* tuple */[
    487210640,
    "md-musical-notes"
  ],
  /* tuple */[
    487210640,
    "md-navigate"
  ],
  /* tuple */[
    487210640,
    "md-notifications"
  ],
  /* tuple */[
    487210640,
    "md-notifications-off"
  ],
  /* tuple */[
    487210640,
    "md-notifications-outline"
  ],
  /* tuple */[
    487210640,
    "md-nuclear"
  ],
  /* tuple */[
    487210640,
    "md-nutrition"
  ],
  /* tuple */[
    487210640,
    "md-open"
  ],
  /* tuple */[
    487210640,
    "md-options"
  ],
  /* tuple */[
    487210640,
    "md-outlet"
  ],
  /* tuple */[
    487210640,
    "md-paper"
  ],
  /* tuple */[
    487210640,
    "md-paper-plane"
  ],
  /* tuple */[
    487210640,
    "md-partly-sunny"
  ],
  /* tuple */[
    487210640,
    "md-pause"
  ],
  /* tuple */[
    487210640,
    "md-paw"
  ],
  /* tuple */[
    487210640,
    "md-people"
  ],
  /* tuple */[
    487210640,
    "md-person"
  ],
  /* tuple */[
    487210640,
    "md-person-add"
  ],
  /* tuple */[
    487210640,
    "md-phone-landscape"
  ],
  /* tuple */[
    487210640,
    "md-phone-portrait"
  ],
  /* tuple */[
    487210640,
    "md-photos"
  ],
  /* tuple */[
    487210640,
    "md-pie"
  ],
  /* tuple */[
    487210640,
    "md-pin"
  ],
  /* tuple */[
    487210640,
    "md-pint"
  ],
  /* tuple */[
    487210640,
    "md-pizza"
  ],
  /* tuple */[
    487210640,
    "md-planet"
  ],
  /* tuple */[
    487210640,
    "md-play"
  ],
  /* tuple */[
    487210640,
    "md-play-circle"
  ],
  /* tuple */[
    487210640,
    "md-podium"
  ],
  /* tuple */[
    487210640,
    "md-power"
  ],
  /* tuple */[
    487210640,
    "md-pricetag"
  ],
  /* tuple */[
    487210640,
    "md-pricetags"
  ],
  /* tuple */[
    487210640,
    "md-print"
  ],
  /* tuple */[
    487210640,
    "md-pulse"
  ],
  /* tuple */[
    487210640,
    "md-qr-scanner"
  ],
  /* tuple */[
    487210640,
    "md-quote"
  ],
  /* tuple */[
    487210640,
    "md-radio"
  ],
  /* tuple */[
    487210640,
    "md-radio-button-off"
  ],
  /* tuple */[
    487210640,
    "md-radio-button-on"
  ],
  /* tuple */[
    487210640,
    "md-rainy"
  ],
  /* tuple */[
    487210640,
    "md-recording"
  ],
  /* tuple */[
    487210640,
    "md-redo"
  ],
  /* tuple */[
    487210640,
    "md-refresh"
  ],
  /* tuple */[
    487210640,
    "md-refresh-circle"
  ],
  /* tuple */[
    487210640,
    "md-remove"
  ],
  /* tuple */[
    487210640,
    "md-remove-circle"
  ],
  /* tuple */[
    487210640,
    "md-remove-circle-outline"
  ],
  /* tuple */[
    487210640,
    "md-reorder"
  ],
  /* tuple */[
    487210640,
    "md-repeat"
  ],
  /* tuple */[
    487210640,
    "md-resize"
  ],
  /* tuple */[
    487210640,
    "md-restaurant"
  ],
  /* tuple */[
    487210640,
    "md-return-left"
  ],
  /* tuple */[
    487210640,
    "md-return-right"
  ],
  /* tuple */[
    487210640,
    "md-reverse-camera"
  ],
  /* tuple */[
    487210640,
    "md-rewind"
  ],
  /* tuple */[
    487210640,
    "md-ribbon"
  ],
  /* tuple */[
    487210640,
    "md-rocket"
  ],
  /* tuple */[
    487210640,
    "md-rose"
  ],
  /* tuple */[
    487210640,
    "md-sad"
  ],
  /* tuple */[
    487210640,
    "md-save"
  ],
  /* tuple */[
    487210640,
    "md-school"
  ],
  /* tuple */[
    487210640,
    "md-search"
  ],
  /* tuple */[
    487210640,
    "md-send"
  ],
  /* tuple */[
    487210640,
    "md-settings"
  ],
  /* tuple */[
    487210640,
    "md-share"
  ],
  /* tuple */[
    487210640,
    "md-share-alt"
  ],
  /* tuple */[
    487210640,
    "md-shirt"
  ],
  /* tuple */[
    487210640,
    "md-shuffle"
  ],
  /* tuple */[
    487210640,
    "md-skip-backward"
  ],
  /* tuple */[
    487210640,
    "md-skip-forward"
  ],
  /* tuple */[
    487210640,
    "md-snow"
  ],
  /* tuple */[
    487210640,
    "md-speedometer"
  ],
  /* tuple */[
    487210640,
    "md-square"
  ],
  /* tuple */[
    487210640,
    "md-square-outline"
  ],
  /* tuple */[
    487210640,
    "md-star"
  ],
  /* tuple */[
    487210640,
    "md-star-half"
  ],
  /* tuple */[
    487210640,
    "md-star-outline"
  ],
  /* tuple */[
    487210640,
    "md-stats"
  ],
  /* tuple */[
    487210640,
    "md-stopwatch"
  ],
  /* tuple */[
    487210640,
    "md-subway"
  ],
  /* tuple */[
    487210640,
    "md-sunny"
  ],
  /* tuple */[
    487210640,
    "md-swap"
  ],
  /* tuple */[
    487210640,
    "md-switch"
  ],
  /* tuple */[
    487210640,
    "md-sync"
  ],
  /* tuple */[
    487210640,
    "md-tablet-landscape"
  ],
  /* tuple */[
    487210640,
    "md-tablet-portrait"
  ],
  /* tuple */[
    487210640,
    "md-tennisball"
  ],
  /* tuple */[
    487210640,
    "md-text"
  ],
  /* tuple */[
    487210640,
    "md-thermometer"
  ],
  /* tuple */[
    487210640,
    "md-thumbs-down"
  ],
  /* tuple */[
    487210640,
    "md-thumbs-up"
  ],
  /* tuple */[
    487210640,
    "md-thunderstorm"
  ],
  /* tuple */[
    487210640,
    "md-time"
  ],
  /* tuple */[
    487210640,
    "md-timer"
  ],
  /* tuple */[
    487210640,
    "md-today"
  ],
  /* tuple */[
    487210640,
    "md-train"
  ],
  /* tuple */[
    487210640,
    "md-transgender"
  ],
  /* tuple */[
    487210640,
    "md-trash"
  ],
  /* tuple */[
    487210640,
    "md-trending-down"
  ],
  /* tuple */[
    487210640,
    "md-trending-up"
  ],
  /* tuple */[
    487210640,
    "md-trophy"
  ],
  /* tuple */[
    487210640,
    "md-tv"
  ],
  /* tuple */[
    487210640,
    "md-umbrella"
  ],
  /* tuple */[
    487210640,
    "md-undo"
  ],
  /* tuple */[
    487210640,
    "md-unlock"
  ],
  /* tuple */[
    487210640,
    "md-videocam"
  ],
  /* tuple */[
    487210640,
    "md-volume-high"
  ],
  /* tuple */[
    487210640,
    "md-volume-low"
  ],
  /* tuple */[
    487210640,
    "md-volume-mute"
  ],
  /* tuple */[
    487210640,
    "md-volume-off"
  ],
  /* tuple */[
    487210640,
    "md-walk"
  ],
  /* tuple */[
    487210640,
    "md-wallet"
  ],
  /* tuple */[
    487210640,
    "md-warning"
  ],
  /* tuple */[
    487210640,
    "md-watch"
  ],
  /* tuple */[
    487210640,
    "md-water"
  ],
  /* tuple */[
    487210640,
    "md-wifi"
  ],
  /* tuple */[
    487210640,
    "md-wine"
  ],
  /* tuple */[
    487210640,
    "md-woman"
  ]
];

function nameToJs(param) {
  return Js_mapperRt.binarySearch(696, param, jsMapperConstantArray);
}

function nameFromJs(param) {
  return Js_mapperRt.revSearch(696, jsMapperConstantArray, param);
}

function make($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, children) {
  var allowFontScaling = $staropt$star !== undefined ? $staropt$star : false;
  var name = $staropt$star$1 !== undefined ? $staropt$star$1 : /* undefined */487210640;
  var color = $staropt$star$2 !== undefined ? $staropt$star$2 : "black";
  var size = $staropt$star$3 !== undefined ? $staropt$star$3 : 12;
  var style = $staropt$star$4 !== undefined ? Caml_option.valFromOption($staropt$star$4) : Style$BsReactNative.style(/* [] */0);
  return ReasonReact.wrapJsForReason(VectorIcons.Ionicons, {
              allowFontScaling: allowFontScaling,
              name: name,
              size: size,
              color: color,
              style: style
            }, children);
}

var Ionicons = /* module */[
  /* nameFromJs */nameFromJs,
  /* nameToJs */nameToJs,
  /* make */make
];

exports.Ionicons = Ionicons;
/* ReasonReact Not a pure module */
