// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var VectorIcons = require("@expo/vector-icons");
var Style$BsReactNative = require("bs-react-native/src/style.js");

function getIcon(x) {
  switch (x) {
    case 0 : 
        return "ios-add";
    case 1 : 
        return "ios-add-circle";
    case 2 : 
        return "ios-add-circle-outline";
    case 3 : 
        return "ios-airplane";
    case 4 : 
        return "ios-alarm";
    case 5 : 
        return "ios-albums";
    case 6 : 
        return "ios-alert";
    case 7 : 
        return "ios-american-football";
    case 8 : 
        return "ios-analytics";
    case 9 : 
        return "ios-aperture";
    case 10 : 
        return "ios-apps";
    case 11 : 
        return "ios-appstore";
    case 12 : 
        return "ios-archive";
    case 13 : 
        return "ios-arrow-back";
    case 14 : 
        return "ios-arrow-down";
    case 15 : 
        return "ios-arrow-dropdown";
    case 16 : 
        return "ios-arrow-dropdown-circle";
    case 17 : 
        return "ios-arrow-dropleft";
    case 18 : 
        return "ios-arrow-dropleft-circle";
    case 19 : 
        return "ios-arrow-dropright";
    case 20 : 
        return "ios-arrow-dropright-circle";
    case 21 : 
        return "ios-arrow-dropup";
    case 22 : 
        return "ios-arrow-dropup-circle";
    case 23 : 
        return "ios-arrow-forward";
    case 24 : 
        return "ios-arrow-round-back";
    case 25 : 
        return "ios-arrow-round-down";
    case 26 : 
        return "ios-arrow-round-forward";
    case 27 : 
        return "ios-arrow-round-up";
    case 28 : 
        return "ios-arrow-up";
    case 29 : 
        return "ios-at";
    case 30 : 
        return "ios-attach";
    case 31 : 
        return "ios-backspace";
    case 32 : 
        return "ios-barcode";
    case 33 : 
        return "ios-baseball";
    case 34 : 
        return "ios-basket";
    case 35 : 
        return "ios-basketball";
    case 36 : 
        return "ios-battery-charging";
    case 37 : 
        return "ios-battery-dead";
    case 38 : 
        return "ios-battery-full";
    case 39 : 
        return "ios-beaker";
    case 40 : 
        return "ios-bed";
    case 41 : 
        return "ios-beer";
    case 42 : 
        return "ios-bicycle";
    case 43 : 
        return "ios-bluetooth";
    case 44 : 
        return "ios-boat";
    case 45 : 
        return "ios-body";
    case 46 : 
        return "ios-bonfire";
    case 47 : 
        return "ios-book";
    case 48 : 
        return "ios-bookmark";
    case 49 : 
        return "ios-bookmarks";
    case 50 : 
        return "ios-bowtie";
    case 51 : 
        return "ios-briefcase";
    case 52 : 
        return "ios-browsers";
    case 53 : 
        return "ios-brush";
    case 54 : 
        return "ios-bug";
    case 55 : 
        return "ios-build";
    case 56 : 
        return "ios-bulb";
    case 57 : 
        return "ios-bus";
    case 58 : 
        return "ios-business";
    case 59 : 
        return "ios-cafe";
    case 60 : 
        return "ios-calculator";
    case 61 : 
        return "ios-calendar";
    case 62 : 
        return "ios-call";
    case 63 : 
        return "ios-camera";
    case 64 : 
        return "ios-car";
    case 65 : 
        return "ios-card";
    case 66 : 
        return "ios-cart";
    case 67 : 
        return "ios-cash";
    case 68 : 
        return "ios-cellular";
    case 69 : 
        return "ios-chatboxes";
    case 70 : 
        return "ios-chatbubbles";
    case 71 : 
        return "ios-checkbox";
    case 72 : 
        return "ios-checkbox-outline";
    case 73 : 
        return "ios-checkmark";
    case 74 : 
        return "ios-checkmark-circle";
    case 75 : 
        return "ios-checkmark-circle-outline";
    case 76 : 
        return "ios-clipboard";
    case 77 : 
        return "ios-clock";
    case 78 : 
        return "ios-close";
    case 79 : 
        return "ios-close-circle";
    case 80 : 
        return "ios-close-circle-outline";
    case 81 : 
        return "ios-cloud";
    case 82 : 
        return "ios-cloud-circle";
    case 83 : 
        return "ios-cloud-done";
    case 84 : 
        return "ios-cloud-download";
    case 85 : 
        return "ios-cloud-outline";
    case 86 : 
        return "ios-cloud-upload";
    case 87 : 
        return "ios-cloudy";
    case 88 : 
        return "ios-cloudy-night";
    case 89 : 
        return "ios-code";
    case 90 : 
        return "ios-code-download";
    case 91 : 
        return "ios-code-working";
    case 92 : 
        return "ios-cog";
    case 93 : 
        return "ios-color-fill";
    case 94 : 
        return "ios-color-filter";
    case 95 : 
        return "ios-color-palette";
    case 96 : 
        return "ios-color-wand";
    case 97 : 
        return "ios-compass";
    case 98 : 
        return "ios-construct";
    case 99 : 
        return "ios-contact";
    case 100 : 
        return "ios-contacts";
    case 101 : 
        return "ios-contract";
    case 102 : 
        return "ios-contrast";
    case 103 : 
        return "ios-copy";
    case 104 : 
        return "ios-create";
    case 105 : 
        return "ios-crop";
    case 106 : 
        return "ios-cube";
    case 107 : 
        return "ios-cut";
    case 108 : 
        return "ios-desktop";
    case 109 : 
        return "ios-disc";
    case 110 : 
        return "ios-document";
    case 111 : 
        return "ios-done-all";
    case 112 : 
        return "ios-download";
    case 113 : 
        return "ios-easel";
    case 114 : 
        return "ios-egg";
    case 115 : 
        return "ios-exit";
    case 116 : 
        return "ios-expand";
    case 117 : 
        return "ios-eye";
    case 118 : 
        return "ios-eye-off";
    case 119 : 
        return "ios-fastforward";
    case 120 : 
        return "ios-female";
    case 121 : 
        return "ios-filing";
    case 122 : 
        return "ios-film";
    case 123 : 
        return "ios-finger-print";
    case 124 : 
        return "ios-fitness";
    case 125 : 
        return "ios-flag";
    case 126 : 
        return "ios-flame";
    case 127 : 
        return "ios-flash";
    case 128 : 
        return "ios-flash-off";
    case 129 : 
        return "ios-flashlight";
    case 130 : 
        return "ios-flask";
    case 131 : 
        return "ios-flower";
    case 132 : 
        return "ios-folder";
    case 133 : 
        return "ios-folder-open";
    case 134 : 
        return "ios-football";
    case 135 : 
        return "ios-funnel";
    case 136 : 
        return "ios-gift";
    case 137 : 
        return "ios-git-branch";
    case 138 : 
        return "ios-git-commit";
    case 139 : 
        return "ios-git-compare";
    case 140 : 
        return "ios-git-merge";
    case 141 : 
        return "ios-git-network";
    case 142 : 
        return "ios-git-pull-request";
    case 143 : 
        return "ios-glasses";
    case 144 : 
        return "ios-globe";
    case 145 : 
        return "ios-grid";
    case 146 : 
        return "ios-hammer";
    case 147 : 
        return "ios-hand";
    case 148 : 
        return "ios-happy";
    case 149 : 
        return "ios-headset";
    case 150 : 
        return "ios-heart";
    case 151 : 
        return "ios-heart-dislike";
    case 152 : 
        return "ios-heart-empty";
    case 153 : 
        return "ios-heart-half";
    case 154 : 
        return "ios-help";
    case 155 : 
        return "ios-help-buoy";
    case 156 : 
        return "ios-help-circle";
    case 157 : 
        return "ios-help-circle-outline";
    case 158 : 
        return "ios-home";
    case 159 : 
        return "ios-hourglass";
    case 160 : 
        return "ios-ice-cream";
    case 161 : 
        return "ios-image";
    case 162 : 
        return "ios-images";
    case 163 : 
        return "ios-infinite";
    case 164 : 
        return "ios-information";
    case 165 : 
        return "ios-information-circle";
    case 166 : 
        return "ios-information-circle-outline";
    case 167 : 
        return "ios-jet";
    case 168 : 
        return "ios-journal";
    case 169 : 
        return "ios-key";
    case 170 : 
        return "ios-keypad";
    case 171 : 
        return "ios-laptop";
    case 172 : 
        return "ios-leaf";
    case 173 : 
        return "ios-link";
    case 174 : 
        return "ios-list";
    case 175 : 
        return "ios-list-box";
    case 176 : 
        return "ios-locate";
    case 177 : 
        return "ios-lock";
    case 178 : 
        return "ios-log-in";
    case 179 : 
        return "ios-log-out";
    case 180 : 
        return "ios-magnet";
    case 181 : 
        return "ios-mail";
    case 182 : 
        return "ios-mail-open";
    case 183 : 
        return "ios-mail-unread";
    case 184 : 
        return "ios-male";
    case 185 : 
        return "ios-man";
    case 186 : 
        return "ios-map";
    case 187 : 
        return "ios-medal";
    case 188 : 
        return "ios-medical";
    case 189 : 
        return "ios-medkit";
    case 190 : 
        return "ios-megaphone";
    case 191 : 
        return "ios-menu";
    case 192 : 
        return "ios-mic";
    case 193 : 
        return "ios-mic-off";
    case 194 : 
        return "ios-microphone";
    case 195 : 
        return "ios-moon";
    case 196 : 
        return "ios-more";
    case 197 : 
        return "ios-move";
    case 198 : 
        return "ios-musical-note";
    case 199 : 
        return "ios-musical-notes";
    case 200 : 
        return "ios-navigate";
    case 201 : 
        return "ios-notifications";
    case 202 : 
        return "ios-notifications-off";
    case 203 : 
        return "ios-notifications-outline";
    case 204 : 
        return "ios-nuclear";
    case 205 : 
        return "ios-nutrition";
    case 206 : 
        return "ios-open";
    case 207 : 
        return "ios-options";
    case 208 : 
        return "ios-outlet";
    case 209 : 
        return "ios-paper";
    case 210 : 
        return "ios-paper-plane";
    case 211 : 
        return "ios-partly-sunny";
    case 212 : 
        return "ios-pause";
    case 213 : 
        return "ios-paw";
    case 214 : 
        return "ios-people";
    case 215 : 
        return "ios-person";
    case 216 : 
        return "ios-person-add";
    case 217 : 
        return "ios-phone-landscape";
    case 218 : 
        return "ios-phone-portrait";
    case 219 : 
        return "ios-photos";
    case 220 : 
        return "ios-pie";
    case 221 : 
        return "ios-pin";
    case 222 : 
        return "ios-pint";
    case 223 : 
        return "ios-pizza";
    case 224 : 
        return "ios-planet";
    case 225 : 
        return "ios-play";
    case 226 : 
        return "ios-play-circle";
    case 227 : 
        return "ios-podium";
    case 228 : 
        return "ios-power";
    case 229 : 
        return "ios-pricetag";
    case 230 : 
        return "ios-pricetags";
    case 231 : 
        return "ios-print";
    case 232 : 
        return "ios-pulse";
    case 233 : 
        return "ios-qr-scanner";
    case 234 : 
        return "ios-quote";
    case 235 : 
        return "ios-radio";
    case 236 : 
        return "ios-radio-button-off";
    case 237 : 
        return "ios-radio-button-on";
    case 238 : 
        return "ios-rainy";
    case 239 : 
        return "ios-recording";
    case 240 : 
        return "ios-redo";
    case 241 : 
        return "ios-refresh";
    case 242 : 
        return "ios-refresh-circle";
    case 243 : 
        return "ios-remove";
    case 244 : 
        return "ios-remove-circle";
    case 245 : 
        return "ios-remove-circle-outline";
    case 246 : 
        return "ios-reorder";
    case 247 : 
        return "ios-repeat";
    case 248 : 
        return "ios-resize";
    case 249 : 
        return "ios-restaurant";
    case 250 : 
        return "ios-return-left";
    case 251 : 
        return "ios-return-right";
    case 252 : 
        return "ios-reverse-camera";
    case 253 : 
        return "ios-rewind";
    case 254 : 
        return "ios-ribbon";
    case 255 : 
        return "ios-rocket";
    case 256 : 
        return "ios-rose";
    case 257 : 
        return "ios-sad";
    case 258 : 
        return "ios-save";
    case 259 : 
        return "ios-school";
    case 260 : 
        return "ios-search";
    case 261 : 
        return "ios-send";
    case 262 : 
        return "ios-settings";
    case 263 : 
        return "ios-share";
    case 264 : 
        return "ios-share-alt";
    case 265 : 
        return "ios-shirt";
    case 266 : 
        return "ios-shuffle";
    case 267 : 
        return "ios-skip-backward";
    case 268 : 
        return "ios-skip-forward";
    case 269 : 
        return "ios-snow";
    case 270 : 
        return "ios-speedometer";
    case 271 : 
        return "ios-square";
    case 272 : 
        return "ios-square-outline";
    case 273 : 
        return "ios-star";
    case 274 : 
        return "ios-star-half";
    case 275 : 
        return "ios-star-outline";
    case 276 : 
        return "ios-stats";
    case 277 : 
        return "ios-stopwatch";
    case 278 : 
        return "ios-subway";
    case 279 : 
        return "ios-sunny";
    case 280 : 
        return "ios-swap";
    case 281 : 
        return "ios-switch";
    case 282 : 
        return "ios-sync";
    case 283 : 
        return "ios-tablet-landscape";
    case 284 : 
        return "ios-tablet-portrait";
    case 285 : 
        return "ios-tennisball";
    case 286 : 
        return "ios-text";
    case 287 : 
        return "ios-thermometer";
    case 288 : 
        return "ios-thumbs-down";
    case 289 : 
        return "ios-thumbs-up";
    case 290 : 
        return "ios-thunderstorm";
    case 291 : 
        return "ios-time";
    case 292 : 
        return "ios-timer";
    case 293 : 
        return "ios-today";
    case 294 : 
        return "ios-train";
    case 295 : 
        return "ios-transgender";
    case 296 : 
        return "ios-trash";
    case 297 : 
        return "ios-trending-down";
    case 298 : 
        return "ios-trending-up";
    case 299 : 
        return "ios-trophy";
    case 300 : 
        return "ios-tv";
    case 301 : 
        return "ios-umbrella";
    case 302 : 
        return "ios-undo";
    case 303 : 
        return "ios-unlock";
    case 304 : 
        return "ios-videocam";
    case 305 : 
        return "ios-volume-high";
    case 306 : 
        return "ios-volume-low";
    case 307 : 
        return "ios-volume-mute";
    case 308 : 
        return "ios-volume-off";
    case 309 : 
        return "ios-walk";
    case 310 : 
        return "ios-wallet";
    case 311 : 
        return "ios-warning";
    case 312 : 
        return "ios-watch";
    case 313 : 
        return "ios-water";
    case 314 : 
        return "ios-wifi";
    case 315 : 
        return "ios-wine";
    case 316 : 
        return "ios-woman";
    case 317 : 
        return "logo-android";
    case 318 : 
        return "logo-angular";
    case 319 : 
        return "logo-apple";
    case 320 : 
        return "logo-bitbucket";
    case 321 : 
        return "logo-bitcoin";
    case 322 : 
        return "logo-buffer";
    case 323 : 
        return "logo-chrome";
    case 324 : 
        return "logo-closed-captioning";
    case 325 : 
        return "logo-codepen";
    case 326 : 
        return "logo-css-3";
    case 327 : 
        return "logo-designernews";
    case 328 : 
        return "logo-dribbble";
    case 329 : 
        return "logo-dropbox";
    case 330 : 
        return "logo-euro";
    case 331 : 
        return "logo-facebook";
    case 332 : 
        return "logo-flickr";
    case 333 : 
        return "logo-foursquare";
    case 334 : 
        return "logo-freebsd-devil";
    case 335 : 
        return "logo-game-controller-a";
    case 336 : 
        return "logo-game-controller-b";
    case 337 : 
        return "logo-github";
    case 338 : 
        return "logo-google";
    case 339 : 
        return "logo-googleplus";
    case 340 : 
        return "logo-hackernews";
    case 341 : 
        return "logo-html-5";
    case 342 : 
        return "logo-instagram";
    case 343 : 
        return "logo-ionic";
    case 344 : 
        return "logo-ionitron";
    case 345 : 
        return "logo-javascript";
    case 346 : 
        return "logo-linkedin";
    case 347 : 
        return "logo-markdown";
    case 348 : 
        return "logo-model-s";
    case 349 : 
        return "logo-no-smoking";
    case 350 : 
        return "logo-nodejs";
    case 351 : 
        return "logo-npm";
    case 352 : 
        return "logo-octocat";
    case 353 : 
        return "logo-pinterest";
    case 354 : 
        return "logo-playstation";
    case 355 : 
        return "logo-polymer";
    case 356 : 
        return "logo-python";
    case 357 : 
        return "logo-reddit";
    case 358 : 
        return "logo-rss";
    case 359 : 
        return "logo-sass";
    case 360 : 
        return "logo-skype";
    case 361 : 
        return "logo-slack";
    case 362 : 
        return "logo-snapchat";
    case 363 : 
        return "logo-steam";
    case 364 : 
        return "logo-tumblr";
    case 365 : 
        return "logo-tux";
    case 366 : 
        return "logo-twitch";
    case 367 : 
        return "logo-twitter";
    case 368 : 
        return "logo-usd";
    case 369 : 
        return "logo-vimeo";
    case 370 : 
        return "logo-vk";
    case 371 : 
        return "logo-whatsapp";
    case 372 : 
        return "logo-windows";
    case 373 : 
        return "logo-wordpress";
    case 374 : 
        return "logo-xbox";
    case 375 : 
        return "logo-xing";
    case 376 : 
        return "logo-yahoo";
    case 377 : 
        return "logo-yen";
    case 378 : 
        return "logo-youtube";
    case 379 : 
        return "md-add";
    case 380 : 
        return "md-add-circle";
    case 381 : 
        return "md-add-circle-outline";
    case 382 : 
        return "md-airplane";
    case 383 : 
        return "md-alarm";
    case 384 : 
        return "md-albums";
    case 385 : 
        return "md-alert";
    case 386 : 
        return "md-american-football";
    case 387 : 
        return "md-analytics";
    case 388 : 
        return "md-aperture";
    case 389 : 
        return "md-apps";
    case 390 : 
        return "md-appstore";
    case 391 : 
        return "md-archive";
    case 392 : 
        return "md-arrow-back";
    case 393 : 
        return "md-arrow-down";
    case 394 : 
        return "md-arrow-dropdown";
    case 395 : 
        return "md-arrow-dropdown-circle";
    case 396 : 
        return "md-arrow-dropleft";
    case 397 : 
        return "md-arrow-dropleft-circle";
    case 398 : 
        return "md-arrow-dropright";
    case 399 : 
        return "md-arrow-dropright-circle";
    case 400 : 
        return "md-arrow-dropup";
    case 401 : 
        return "md-arrow-dropup-circle";
    case 402 : 
        return "md-arrow-forward";
    case 403 : 
        return "md-arrow-round-back";
    case 404 : 
        return "md-arrow-round-down";
    case 405 : 
        return "md-arrow-round-forward";
    case 406 : 
        return "md-arrow-round-up";
    case 407 : 
        return "md-arrow-up";
    case 408 : 
        return "md-at";
    case 409 : 
        return "md-attach";
    case 410 : 
        return "md-backspace";
    case 411 : 
        return "md-barcode";
    case 412 : 
        return "md-baseball";
    case 413 : 
        return "md-basket";
    case 414 : 
        return "md-basketball";
    case 415 : 
        return "md-battery-charging";
    case 416 : 
        return "md-battery-dead";
    case 417 : 
        return "md-battery-full";
    case 418 : 
        return "md-beaker";
    case 419 : 
        return "md-bed";
    case 420 : 
        return "md-beer";
    case 421 : 
        return "md-bicycle";
    case 422 : 
        return "md-bluetooth";
    case 423 : 
        return "md-boat";
    case 424 : 
        return "md-body";
    case 425 : 
        return "md-bonfire";
    case 426 : 
        return "md-book";
    case 427 : 
        return "md-bookmark";
    case 428 : 
        return "md-bookmarks";
    case 429 : 
        return "md-bowtie";
    case 430 : 
        return "md-briefcase";
    case 431 : 
        return "md-browsers";
    case 432 : 
        return "md-brush";
    case 433 : 
        return "md-bug";
    case 434 : 
        return "md-build";
    case 435 : 
        return "md-bulb";
    case 436 : 
        return "md-bus";
    case 437 : 
        return "md-business";
    case 438 : 
        return "md-cafe";
    case 439 : 
        return "md-calculator";
    case 440 : 
        return "md-calendar";
    case 441 : 
        return "md-call";
    case 442 : 
        return "md-camera";
    case 443 : 
        return "md-car";
    case 444 : 
        return "md-card";
    case 445 : 
        return "md-cart";
    case 446 : 
        return "md-cash";
    case 447 : 
        return "md-cellular";
    case 448 : 
        return "md-chatboxes";
    case 449 : 
        return "md-chatbubbles";
    case 450 : 
        return "md-checkbox";
    case 451 : 
        return "md-checkbox-outline";
    case 452 : 
        return "md-checkmark";
    case 453 : 
        return "md-checkmark-circle";
    case 454 : 
        return "md-checkmark-circle-outline";
    case 455 : 
        return "md-clipboard";
    case 456 : 
        return "md-clock";
    case 457 : 
        return "md-close";
    case 458 : 
        return "md-close-circle";
    case 459 : 
        return "md-close-circle-outline";
    case 460 : 
        return "md-cloud";
    case 461 : 
        return "md-cloud-circle";
    case 462 : 
        return "md-cloud-done";
    case 463 : 
        return "md-cloud-download";
    case 464 : 
        return "md-cloud-outline";
    case 465 : 
        return "md-cloud-upload";
    case 466 : 
        return "md-cloudy";
    case 467 : 
        return "md-cloudy-night";
    case 468 : 
        return "md-code";
    case 469 : 
        return "md-code-download";
    case 470 : 
        return "md-code-working";
    case 471 : 
        return "md-cog";
    case 472 : 
        return "md-color-fill";
    case 473 : 
        return "md-color-filter";
    case 474 : 
        return "md-color-palette";
    case 475 : 
        return "md-color-wand";
    case 476 : 
        return "md-compass";
    case 477 : 
        return "md-construct";
    case 478 : 
        return "md-contact";
    case 479 : 
        return "md-contacts";
    case 480 : 
        return "md-contract";
    case 481 : 
        return "md-contrast";
    case 482 : 
        return "md-copy";
    case 483 : 
        return "md-create";
    case 484 : 
        return "md-crop";
    case 485 : 
        return "md-cube";
    case 486 : 
        return "md-cut";
    case 487 : 
        return "md-desktop";
    case 488 : 
        return "md-disc";
    case 489 : 
        return "md-document";
    case 490 : 
        return "md-done-all";
    case 491 : 
        return "md-download";
    case 492 : 
        return "md-easel";
    case 493 : 
        return "md-egg";
    case 494 : 
        return "md-exit";
    case 495 : 
        return "md-expand";
    case 496 : 
        return "md-eye";
    case 497 : 
        return "md-eye-off";
    case 498 : 
        return "md-fastforward";
    case 499 : 
        return "md-female";
    case 500 : 
        return "md-filing";
    case 501 : 
        return "md-film";
    case 502 : 
        return "md-finger-print";
    case 503 : 
        return "md-fitness";
    case 504 : 
        return "md-flag";
    case 505 : 
        return "md-flame";
    case 506 : 
        return "md-flash";
    case 507 : 
        return "md-flash-off";
    case 508 : 
        return "md-flashlight";
    case 509 : 
        return "md-flask";
    case 510 : 
        return "md-flower";
    case 511 : 
        return "md-folder";
    case 512 : 
        return "md-folder-open";
    case 513 : 
        return "md-football";
    case 514 : 
        return "md-funnel";
    case 515 : 
        return "md-gift";
    case 516 : 
        return "md-git-branch";
    case 517 : 
        return "md-git-commit";
    case 518 : 
        return "md-git-compare";
    case 519 : 
        return "md-git-merge";
    case 520 : 
        return "md-git-network";
    case 521 : 
        return "md-git-pull-request";
    case 522 : 
        return "md-glasses";
    case 523 : 
        return "md-globe";
    case 524 : 
        return "md-grid";
    case 525 : 
        return "md-hammer";
    case 526 : 
        return "md-hand";
    case 527 : 
        return "md-happy";
    case 528 : 
        return "md-headset";
    case 529 : 
        return "md-heart";
    case 530 : 
        return "md-heart-dislike";
    case 531 : 
        return "md-heart-empty";
    case 532 : 
        return "md-heart-half";
    case 533 : 
        return "md-help";
    case 534 : 
        return "md-help-buoy";
    case 535 : 
        return "md-help-circle";
    case 536 : 
        return "md-help-circle-outline";
    case 537 : 
        return "md-home";
    case 538 : 
        return "md-hourglass";
    case 539 : 
        return "md-ice-cream";
    case 540 : 
        return "md-image";
    case 541 : 
        return "md-images";
    case 542 : 
        return "md-infinite";
    case 543 : 
        return "md-information";
    case 544 : 
        return "md-information-circle";
    case 545 : 
        return "md-information-circle-outline";
    case 546 : 
        return "md-jet";
    case 547 : 
        return "md-journal";
    case 548 : 
        return "md-key";
    case 549 : 
        return "md-keypad";
    case 550 : 
        return "md-laptop";
    case 551 : 
        return "md-leaf";
    case 552 : 
        return "md-link";
    case 553 : 
        return "md-list";
    case 554 : 
        return "md-list-box";
    case 555 : 
        return "md-locate";
    case 556 : 
        return "md-lock";
    case 557 : 
        return "md-log-in";
    case 558 : 
        return "md-log-out";
    case 559 : 
        return "md-magnet";
    case 560 : 
        return "md-mail";
    case 561 : 
        return "md-mail-open";
    case 562 : 
        return "md-mail-unread";
    case 563 : 
        return "md-male";
    case 564 : 
        return "md-man";
    case 565 : 
        return "md-map";
    case 566 : 
        return "md-medal";
    case 567 : 
        return "md-medical";
    case 568 : 
        return "md-medkit";
    case 569 : 
        return "md-megaphone";
    case 570 : 
        return "md-menu";
    case 571 : 
        return "md-mic";
    case 572 : 
        return "md-mic-off";
    case 573 : 
        return "md-microphone";
    case 574 : 
        return "md-moon";
    case 575 : 
        return "md-more";
    case 576 : 
        return "md-move";
    case 577 : 
        return "md-musical-note";
    case 578 : 
        return "md-musical-notes";
    case 579 : 
        return "md-navigate";
    case 580 : 
        return "md-notifications";
    case 581 : 
        return "md-notifications-off";
    case 582 : 
        return "md-notifications-outline";
    case 583 : 
        return "md-nuclear";
    case 584 : 
        return "md-nutrition";
    case 585 : 
        return "md-open";
    case 586 : 
        return "md-options";
    case 587 : 
        return "md-outlet";
    case 588 : 
        return "md-paper";
    case 589 : 
        return "md-paper-plane";
    case 590 : 
        return "md-partly-sunny";
    case 591 : 
        return "md-pause";
    case 592 : 
        return "md-paw";
    case 593 : 
        return "md-people";
    case 594 : 
        return "md-person";
    case 595 : 
        return "md-person-add";
    case 596 : 
        return "md-phone-landscape";
    case 597 : 
        return "md-phone-portrait";
    case 598 : 
        return "md-photos";
    case 599 : 
        return "md-pie";
    case 600 : 
        return "md-pin";
    case 601 : 
        return "md-pint";
    case 602 : 
        return "md-pizza";
    case 603 : 
        return "md-planet";
    case 604 : 
        return "md-play";
    case 605 : 
        return "md-play-circle";
    case 606 : 
        return "md-podium";
    case 607 : 
        return "md-power";
    case 608 : 
        return "md-pricetag";
    case 609 : 
        return "md-pricetags";
    case 610 : 
        return "md-print";
    case 611 : 
        return "md-pulse";
    case 612 : 
        return "md-qr-scanner";
    case 613 : 
        return "md-quote";
    case 614 : 
        return "md-radio";
    case 615 : 
        return "md-radio-button-off";
    case 616 : 
        return "md-radio-button-on";
    case 617 : 
        return "md-rainy";
    case 618 : 
        return "md-recording";
    case 619 : 
        return "md-redo";
    case 620 : 
        return "md-refresh";
    case 621 : 
        return "md-refresh-circle";
    case 622 : 
        return "md-remove";
    case 623 : 
        return "md-remove-circle";
    case 624 : 
        return "md-remove-circle-outline";
    case 625 : 
        return "md-reorder";
    case 626 : 
        return "md-repeat";
    case 627 : 
        return "md-resize";
    case 628 : 
        return "md-restaurant";
    case 629 : 
        return "md-return-left";
    case 630 : 
        return "md-return-right";
    case 631 : 
        return "md-reverse-camera";
    case 632 : 
        return "md-rewind";
    case 633 : 
        return "md-ribbon";
    case 634 : 
        return "md-rocket";
    case 635 : 
        return "md-rose";
    case 636 : 
        return "md-sad";
    case 637 : 
        return "md-save";
    case 638 : 
        return "md-school";
    case 639 : 
        return "md-search";
    case 640 : 
        return "md-send";
    case 641 : 
        return "md-settings";
    case 642 : 
        return "md-share";
    case 643 : 
        return "md-share-alt";
    case 644 : 
        return "md-shirt";
    case 645 : 
        return "md-shuffle";
    case 646 : 
        return "md-skip-backward";
    case 647 : 
        return "md-skip-forward";
    case 648 : 
        return "md-snow";
    case 649 : 
        return "md-speedometer";
    case 650 : 
        return "md-square";
    case 651 : 
        return "md-square-outline";
    case 652 : 
        return "md-star";
    case 653 : 
        return "md-star-half";
    case 654 : 
        return "md-star-outline";
    case 655 : 
        return "md-stats";
    case 656 : 
        return "md-stopwatch";
    case 657 : 
        return "md-subway";
    case 658 : 
        return "md-sunny";
    case 659 : 
        return "md-swap";
    case 660 : 
        return "md-switch";
    case 661 : 
        return "md-sync";
    case 662 : 
        return "md-tablet-landscape";
    case 663 : 
        return "md-tablet-portrait";
    case 664 : 
        return "md-tennisball";
    case 665 : 
        return "md-text";
    case 666 : 
        return "md-thermometer";
    case 667 : 
        return "md-thumbs-down";
    case 668 : 
        return "md-thumbs-up";
    case 669 : 
        return "md-thunderstorm";
    case 670 : 
        return "md-time";
    case 671 : 
        return "md-timer";
    case 672 : 
        return "md-today";
    case 673 : 
        return "md-train";
    case 674 : 
        return "md-transgender";
    case 675 : 
        return "md-trash";
    case 676 : 
        return "md-trending-down";
    case 677 : 
        return "md-trending-up";
    case 678 : 
        return "md-trophy";
    case 679 : 
        return "md-tv";
    case 680 : 
        return "md-umbrella";
    case 681 : 
        return "md-undo";
    case 682 : 
        return "md-unlock";
    case 683 : 
        return "md-videocam";
    case 684 : 
        return "md-volume-high";
    case 685 : 
        return "md-volume-low";
    case 686 : 
        return "md-volume-mute";
    case 687 : 
        return "md-volume-off";
    case 688 : 
        return "md-walk";
    case 689 : 
        return "md-wallet";
    case 690 : 
        return "md-warning";
    case 691 : 
        return "md-watch";
    case 692 : 
        return "md-water";
    case 693 : 
        return "md-wifi";
    case 694 : 
        return "md-wine";
    case 695 : 
        return "md-woman";
    
  }
}

function make($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, children) {
  var allowFontScaling = $staropt$star !== undefined ? $staropt$star : false;
  var name = $staropt$star$1 !== undefined ? $staropt$star$1 : /* IosAdd */0;
  var color = $staropt$star$2 !== undefined ? $staropt$star$2 : "black";
  var size = $staropt$star$3 !== undefined ? $staropt$star$3 : 12;
  var style = $staropt$star$4 !== undefined ? Caml_option.valFromOption($staropt$star$4) : Style$BsReactNative.style(/* [] */0);
  return ReasonReact.wrapJsForReason(VectorIcons.Ionicons, {
              allowFontScaling: allowFontScaling,
              name: getIcon(name),
              size: size,
              color: color,
              style: style
            }, children);
}

var Ionicons = /* module */[
  /* getIcon */getIcon,
  /* make */make
];

exports.Ionicons = Ionicons;
/* ReasonReact Not a pure module */
